### ISSUE TITLE
Principle #6 definitions - automated validation

### ISSUE THREAD

**Issue by beckyjackson** [OBOFoundry/OBOFoundry.github.io#1010]
FP 6 - Textual Definitions

Automated checks:
1. Each definition must be unique
2. No entity may have more than one defintion
3. Each entity should have a definition
4. Definitions should follow Aristotelian form

Mechanism:

Checks 1 through 3 are implemented by [ROBOT report](http://robot.obolibrary.org/report). We can run the report and look at the results of these three checks. The first two (duplicate and multiple definitions) are failures. The third (missing definitions) is a warning.

Check 4 is a bit more difficult to implement and I'm not sure if it is practical to do this right now.

**Comment by nataled** [comment]
From EWG discussion on this:

Need to account for special cases (like structures in CHEBI) or alternatives to definitions (such as elucidations in BFO).

**Comment by beckyjackson** [comment]
ROBOT's `report` checks for elucidations as well, for example: http://robot.obolibrary.org/report_queries/missing_definition

We do not have a special case for ChEBI structures though. What is the relevant property for this? Are there other special cases that we need to consider?

**Comment by nataled** [comment]
The CHEBI case and BFO cases were the only ones discussed (these discussions happened several years ago, well before there even was ROBOT, and I just wanted to bring the discussion out of the internal document and into the tracker). 

I don't know what the relevant property would be. Not sure there even is one to look for. But, we knew that CHEBI (and probably the new glycan ontology) would have problems meeting this principle due to the nature of their "definitions."

**Comment by nataled** [comment]
Closed because the automated check is already in place and functioning properly for nearly all ontologies, with only CHEBI as an exception. A separate ticket has been opened for that (#1802).
