### ISSUE TITLE
REO - Reagent Ontology 

### ISSUE THREAD

**Issue by bpeters42** [OBOFoundry/OBOFoundry.github.io#1042]
OBI has been using some terms with REO namespace identifiers (https://github.com/obi-ontology/obi/issues/1015). It does not seem like the REO ontology is registered. We would like to migrate these to OBI identifiers, but wanted to check in with @mellybelly @mbrush

**Comment by nlharris** [comment]
It looks like this one is waiting for a response from @mellybelly?

**Comment by mellybelly** [comment]
@mbrush can you assist in helping get some of the REO content migrated officially into OBI? It does not seem like it is worth it at this point to register REO since it is not being maintained. Happy to help review. @bpeters42 if recall the modeling was indeed consistent and should be straightforward.

**Comment by bpeters42** [comment]
Thanks Melissa! Matt: all we would need is a link / file of the most up to date version of REO. We could extract from that the terms that are currently in OBI and migrate them, and at the same time review for additional terms that could fill OBI gaps. And we would want to obviously credit the source of the terms, so also let us know who / how you would prefer us to capture that.

**Comment by nlharris** [comment]
I don't see REO on obofoundry.org, so I don't see why "obsoletion" is the right label.

**Comment by mbrush** [comment]
Hi all.  Happy to share where we left off with the Reagent Ontology.  While as a whole the ontology has some pervasive issues (e.g. baroque axiomatization, scope creep, outdated modeling, etc.), and hasn’t been developed at all in the past 8 years, I hope there is some valuable content that might be ceded to OBI or other actively developed ontologies. 
 
I created a [Reagent Ontology archive Github repository](https://github.com/tis-lab/reagent-ontology) to host some ontology files and documentation.  The best file to explore if you want to poke around the ontology itself is the [pre-reasoned version here](https://github.com/tis-lab/reagent-ontology/blob/master/reo/ontology_files/reo_pre-merged_or_reasoned_files/reo_reasoned_9-6-12.owl). The central hierarchy rooted at the 'reagent' class is what you will want to explore - but it is built only upon running a reasoned over the ontology to collect all classes with a reagent role in one place. This pre-reasoned version is useful because ReO's baroque axiomatization of classes in the ontology make reasoning in Protégé prohibitively slow (at least with the most common Protege reasoner plugins).

Happy to answer any questions as best I can.

**Comment by jamesaoverton** [comment]
Closing this in favour of an OBI tracker issue: https://github.com/obi-ontology/obi/issues/1135
