### ISSUE TITLE
incorrect external link

### ISSUE THREAD

**Issue by melissaclarkson** [OBOFoundry/OBOFoundry.github.io#1053]
On the Relations Ontology page (http://www.obofoundry.org/ontology/ro.html), the link for AberOWL goes to the Radiomics Ontology.

**Comment by tophat8855** [comment]
I see that the id for the Relations Ontology on OBO is 'RO' but on AberOWL it is 'RELO'.  The AberOWL link goes to the Radiomics Ontology because there it has the 'RO' id.

I have a suggested change for making an optional `aberowl_id` for ontologies because this might be an issue for other ontologies. I'll attach the PR here, but I also understand that if this is not particularly common, this change may be too much.

**Comment by jamesaoverton** [comment]
Thanks for PR #1067 @tophat8855. I can see how that PR solves the problem. But it bothers me that the OBO Registry should encode and maintain an exception like this just because AberOWL made a strange design decision. My general point is that little exceptions like this add up, until we're paying a significant complexity cost on behalf of other projects.

This is a small change, and maybe it's worth it in this case.

**Comment by cmungall** [comment]
We know we have to do something similar for bioportal

Given AberOWL is a bit more OBO-centric I wonder if we could resolve this just by aligning on prefixes, cc @leechuck @reality

**Comment by leechuck** [comment]
I think the easiest would be to change the way AberOWL handles prefixes. @aliraza995 could you have a look?

**Comment by aliraza995** [comment]
@leechuck Seems like the problem was bioportal ontology titles were overridding the ontology title for the same acronym from obo foundry in AberOWL. I have fixed the issue.

**Comment by cmungall** [comment]
Thanks @leechuck and @aliraza995!
