### ISSUE TITLE
FOBI (Food-Biomarker Ontology)

### ISSUE THREAD

**Issue by pcastellanoescuder** [OBOFoundry/OBOFoundry.github.io#1055]
## Ontology title
Food-Biomarker Ontology
## Requested ID space
fobi
## Ontology location
 https://github.com/pcastellanoescuder/FoodBiomarkerOntology
## Contact person
Name: Pol Castellano Escuder
Email address: polcaes@gmail.com
GitHub username: pcastellanoescuder
## Issue tracker
 https://github.com/pcastellanoescuder/FoodBiomarkerOntology/issues
## Ontology license
- [x] CC-BY (version 3 or later)
## Available ontology formats
The FOBI is available in both **OBO** and **OWL** formats.
## What domain is the ontology intended to cover?
The FOBI intend to cover the relationships between foods and metabolites (food-intake biomarkers). This relationships are very heterogeneous and unclear among different research groups so we want to cover this issue.
## Related OBO Foundry ontologies
FoodOn and ChEBI.
## Data source
To design the FOBI we used FooDB, ChemOnt, HMDB and ChEBI.
## Additional comments or remarks

**Comment by jamesaoverton** [comment]
See email discussion here: https://groups.google.com/forum/#!topic/obo-discuss/f1lrt_wVpZY

**Comment by ramonawalls** [comment]
We discussed this request at the OBO Operations meeting today. We are still concerned about the duplication of efforts and the failure to reuse existing ontology terms where possible.

We understand from the email exchange with Damian Dooley that you have plans to incorporate terms from FOODON and CheBI, but we would prefer to see some good faith effort of importing those terms before a PURL is issued, especially because this is a student project and therefore runs a high risk of becoming obsolete in the future, if your plans or research interests change. It is quite a lot of work for our volunteer technical working group to track down the owners of ontologies that are no longer maintained and keep the the metadata up to date.

Before we can issue a PURL for FOBI, could you please clarify what is novel about this ontology, compared to FOODON, such that is requires a separate name space, and how it relates to FOODON? Also, please demonstrate some preliminary efforts at least to import existing ontology terms. We do not expect the ontology to be fully finished, but some good faith effort, and some tracker issues describing how you plan to import terms would be great.

**Comment by pcastellanoescuder** [comment]
Dear Ramona,

Thank you so much for your comments, I understand all of your concerns. It is very important for us to be part of OBO Foundry, that is why we have already started working on the unification and reuse of coincident terms between FOBI, ​​FoodOn and CHEBI.

About the novelty of FOBI, ​​we have sent the paper this week to the journal, so we will be happy to share our pre-print for details during this week. In addition, FOBI items are already indexed in databases such as Human Metabolome Database or FooDB.

However, in short summary, FOBI has the relationships between foods (FoodOn items) and metabolites **found in different biofluids after having consumed different foods (it does not contain the compounds present in each food)**. In addition, due to all the biochemical modifications of the compounds in the organism, most of FOBI metabolites are not found in CHEBI (the coincidence is only about 30% approx.).

We look forward to providing these preliminary efforts very soon.

**Comment by jamesaoverton** [comment]
I believe we have a registry and PURL config file.
