### ISSUE TITLE
domain group attribution 

### ISSUE THREAD

**Issue by mellybelly** [OBOFoundry/OBOFoundry.github.io#1096]
It would be great if we had a mechanism to create an OBO-wide group attribution process. For example, we are going to be requesting a lot of terms for the KPMP project in HPO, Uberon, CL, PATO, etc.. Some potential features:

- [ ] share issue tags across the ontologies (see HPO for KPMP example)
- [ ] be able to create an project dashboard for KPMP requests in OBO ontologies
- [ ] list contributors to the KPMP group attribution by their ORCIDs
- [ ] reference a unique ID for the group in the ontologies that could be expanded to the individual ORCIDs as needed
- [ ] create a landing page for the group with the participants listed and other information
- [ ] be able to query across the ontologies for contributions by the group

**Comment by matentzn** [comment]
I am not 100% sure we are talking about the same thing, but what I would like to contribute to is some mechanism by which we can exactly measure the impact of a grant, or at least a group/project, OBO wide. For example, OpenTargets funds the evolution of EFO. EFO money and personnel contribute to ontologies such as Mondo, Uberon ond GO - but how exactly EFO, in their impact summary, say something like: created/corrected X definitions in Uberon, helped fixing X relationships in Mondo etc etc, is very unclear. And the concepts of groups here can be quite complicated: maybe EBI wants to know how much impact they had on OBO, and EFO is an EBI project. I also feel the ORCID system has a bit the shortcoming that people come and go (change institutions), which makes reconstructing impact extra difficult. Anyways, not sure this is what you are talking about here, but I am very keen to help establishing something along these lines. My hope is that, if projects and groups actually get the proper recognition (both for contributing AND fixing content in upstream OBO ontologies), they might be inclined to do it more, rather than baking their own bread!

**Comment by dosumis** [comment]
I think that tracking individual and group/funcer contributions are related issues and that it is important we can do both.  Simply using ORCIDs & some kind of standard group/funder identifier for xrefs would go a long way.

Within GO, Ruth Lovering's group have been religious about making sure all terms they contribute to get a tag that allows them to provide reports to funders, e.g. the xref GOC:BHF drives this badge on QuickGO: 

![image](https://user-images.githubusercontent.com/112839/72733268-68a18780-3b8f-11ea-8bd1-eaa173f14fa7.png)
https://www.ebi.ac.uk/QuickGO/term/GO:0086014

**Comment by nlharris** [comment]
Just wondering if this is still something desired and actionable.

**Comment by matentzn** [comment]
Maybe this is best solved bottom up (rather than OBO-down). In our side of the World we know promote the use of dcterms:contributor plus orcid IRI for attribution, and ROR/Wikidata for groups. Very simple as APs on terms.. I encourage everyone to just adopt this practice, either by just doing it or by adding a SPARQL construct to the release process that have to augment whatever they use (iao, dce, dcterms:creator, created_by) to dcterms:contributor. Tools that show attribution will just look there.

**Comment by matentzn** [comment]
In any case this is an OMO, not an OBO ticket, and OMO one is here: https://github.com/information-artifact-ontology/ontology-metadata/issues/93

**Comment by nlharris** [comment]
so then can this ticket be closed?
