### ISSUE TITLE
Prefix Request: ontology metadata (OM)

### ISSUE THREAD

**Issue by zhengj2007** [OBOFoundry/OBOFoundry.github.io#1149]
## Ontology title
Ontology Metadata

## Requested ID space
OM

## Ontology location
https://github.com/information-artifact-ontology/ontology-metadata

## Contact person
Name: Chris Mungall 
Email address: cjmungall@lbl.gov
GitHub username: @cmungall

## Issue tracker
https://github.com/information-artifact-ontology/ontology-metadata/issues

## Ontology license

- [x] CC0 (public domain)
- [ ] CC-BY (version 3 or later)
- [ ] Other: *please specify*

## Available ontology formats
OWL

## What domain is the ontology intended to cover?
primary annotation terms for all OBO ontologies

## Intended use/related projects
The goal is to separate metadata OWL file from Information Artifact Ontology (IAO). An independent ontology will be used to hold the terms used as annotations of ontology terms for all OBO ontologies. So, it can be released as needed rather than bound to IAO.

**Comment by mellybelly** [comment]
+1 thrilled to see this separated out!

**Comment by cmungall** [comment]
There was a point on the list about conflicting prefixes, OM is not very unique globally.

 - OMO : for Ontology Metadata Ontology 
 - OOM : OBO Ontology Metadata
 - OMBO : Ontology Metadata for Bio Ontologies
 
License: A lot of us have expressed preference for CC-0 but we need to track previous contributors and check OK

**Comment by jonquet** [comment]
Why not build on convergence with MOD ? 
https://github.com/sifrproject/MOD-Ontology
@biswanathdutta

We have already reviewed 23 vocabularies/ontologies to capture ontology metadata...  are we sure we need one more ?
We are talking here broader scope than the OBO Foundry initiative or biomedical ontologies...  we all (as a ontology community) need to converge toward some kind of W3C Recommendation...  or alike.

**Comment by jamesaoverton** [comment]
Thanks @jonquet and @graybeal for pointing to MOD. I admit that I was not aware of it, and it looks very good.

In my opinion, OBO does not do a good enough job reusing existing standards, and we need to do better.

However this prefix request may actually get us closer to that goal. A lot of OBO metadata terms are in IAO, but IAO has much wider scope. Importing all of IAO does not make sense if you just want to use some annotation properties. That's why the stated goal for this request is "to separate metadata OWL file from Information Artifact Ontology (IAO)" for easier imports/reuse. Our hope is that the ontology metadata can then evolve separately from IAO. I would like to see it evolve towards things like MOD.

**Comment by jonquet** [comment]
In fact, we reviewed 522 properties from 23 metadata vocabularies, considered 346 of them as relevant for ontologies and then "merged them" in a subset of 127 properties that form the AgroPortal metadata model (not yet aligned with MOD proposition at this time). 
https://link.springer.com/article/10.1007/s13740-018-0091-5/tables/3

On these 127 properties 
... that are now also all in MOD1.4: https://github.com/sifrproject/MOD-Ontology/tree/mod-1.4 
only 26 of them have to be defined in the mod namespace... because no other vocabulary would offer them (some will come from our review of what was implemented within ontology repositories). 

So basically, it means that we DO NOT need to create another namespace to host properties unless really necessary. I agree that we need a better name space for MOD also (@biswanathdutta and I were looking at https://w3id.org/ last year but did not finish). 
 
One do not need to "import" (as owl:imports) an ontology to use AnnotationProperty... Only the namespace declaration is needed.

My point is just that I believe what we need is good "guidelines" on what to do with ontology metadata and the OBO foundry community is good at providing good guidelines... so I will more advocate for a good web page explaining what to do an offering examples to copy/paste in an Owl file rather than another metadata ontology. 

On another point, I do agree IAO was not included in our first review... in 2016 but we did look at http://obofoundry.github.io/registry/context.jsonld.

**Comment by matentzn** [comment]
I think I need some clarification on the use case of OMO to judge this. I really like the idea of how MOD was created from an empirical perspective - it gives a reach set of annotations for all important properties, as determined through rigorous empirical investigation. My main hope when I saw this ontology (OMO) being suggested was that it actually offers a tiny (as in microscopic) vocabulary of OBO recommended annotation properties (using standard properties as much as possible) that can, as a whole, be imported into OBO ontologies and be used to  do the most basic annotation stuff, the idea being: hey, use this license property (dc:license), this description property, etc, not that one (dc:rights). What is the scope of OMO? Maybe someone could say something more clearly about the scope and use case *independent of the splitting from IAO*, as the current description is very vague: 
- `The goal is to separate metadata OWL file from Information Artifact Ontology (IAO)`. -> Why is that important? 
- `An independent ontology will be used to hold the terms used as annotations of ontology terms for all OBO ontologies`.  -> Why is that good?
- `So, it can be released as needed rather than bound to IAO.` -> Difficult to understand the motivation and what that means.

Where does OMO start and where does it end (compared to say MOD)?

**Comment by ddooley** [comment]
@jonquet I looked into MOD again - is it fair to say it is metadata about an ontology, rather than curation annotations about terms themselves?  

And to OBOFoundry folks, is the intent of OMO mainly to have a stand-alone set of term curation annotations (mainly from IAO right now), rather than metadata annotations about ontology as a whole? I see OMO has one ontology module branch of stand-alone module types that is the exception to this.

If so, the two are mainly complementary.

**Comment by graybeal** [comment]
Thank you @ddooley for this overview. It would be truly optimal if the two could be designed to be complementary along the lines you suggest—I would really hope OMO wouldn't need to repeat the work undertaken with MOD to analyze the landscape of metadata about ontologies. (That is totally the focus of MOD, as I understand it.)

**Comment by jonquet** [comment]
@ddooley Yes MOD is for metadata about an ontology (or any semantic artifacts/resource in general); it does not offer metadata properties to describe terms themselves

If OMO purpose if to standardize the way terms are being described, then yes.. it could make sense to extract that part from IAO. 
I would recommend to stay as close as possible from PROV-O and PAV but that's another story. 
In that case OMO shall better be called "Term Metadata Ontology" no @cmungall ?

**Comment by zhengj2007** [comment]
Discussed on Mar 24th OBO Foundry operation meeting and decided the ontology title as:  OBO Metadata Ontology (OMO).

**Comment by bpeters42** [comment]
Discussed once more on the call 4/21. Much of the remaining discussions are about content and future alignment of OMO with other metadata standards. Separating it out from IAO, which this ticket is about, is not controversial. The pull request is going forward; closing this.
