### ISSUE TITLE
Create Code of Conduct

### ISSUE THREAD

**Issue by mellybelly** [OBOFoundry/OBOFoundry.github.io#1163]
As a longstanding, mature organization - and one that wants to be welcoming to everyone - I recommend that OBO have a Code of Conduct. I will start a draft and link it here for community editing and review.

**Comment by mellybelly** [comment]
took a stab here: https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1164

**Comment by cmungall** [comment]
I think this is a good thing. Many collaborative open software projects analogous to OBO have adopted CoCs, e.g.

 * https://www.mozilla.org/en-US/about/governance/policies/participation/
 * https://github.blog/2015-07-20-adopting-the-open-code-of-conduct/
 * https://opensource.guide/code-of-conduct/

**Comment by nlharris** [comment]
See my comment in #1164. It's great that Melissa took the initiative to do this! I'm just wondering whether it might make sense to start establishing community-standard CoCs that organizations could reference and then list any modifications, rather than starting their own CoCs from scratch. Could be analogous to licenses. Maybe this is already a thing; I don't know but would be curious to learn.

**Comment by cmungall** [comment]
See https://github.com/INCATools/ontology-development-kit/issues/331 if we want to add a template to ODK

**Comment by nlharris** [comment]
The initial CoC has been merged (https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1164) -- does that mean we can close this issue?

**Comment by nlharris** [comment]
I like my suggestion on March 21, though it's out of scope for the OBO Foundry.

**Comment by nlharris** [comment]
Based on @ramonawalls's comment in #1164 in May, it seems like we can close this issue, since at least an initial CoC has been created and approved by the Operations Committee?
