### ISSUE TITLE
New governance principle for contributions?

### ISSUE THREAD

**Issue by mellybelly** [OBOFoundry/OBOFoundry.github.io#1165]
It would be terrific to improve the governance of individual ontologies as well as the OBO Library more generally.  

Having a new principle and/or other governance and decision-making documentation would be a great way to advance our consistency of process as a complement to other efforts to ensure interoperability and consistency. 

These ideas specifically relate to governance over contributions:
1 ) a clear statement that the ontology welcomes community contribution in the form of pull requests, and how many +1s (other process) are needed to accept the term
2) a clear statement how an id range can be obtained
3) a clear statement for acceptable conditions for rejecting a term
4) a number of days, weeks before an un-reviewed PR can be merged (by someone with write access)
5) conditions under which you get write access (can be super tight, like developers only)
6) contribution attribution policy (orcids on terms, use of [OBO citation policy](http://www.obofoundry.org/docs/Citation.html), recommendation to use Contribution Role [Ontology](http://www.obofoundry.org/ontology/cro.html)
7) a clear commitment to semantics over convenience for users when it comes to axiomatization (my software only knows isa, so "bear family" isa "bear"). This is hard, and mostly important for the justifying fixes to the axiomatic structure. This is partially addressed with commitment to use RO and the new OBO Core.
8) a commitment that issues will not be closed without a fix or a constructive reason or community decision.

**Comment by nataled** [comment]
@balhoff as chair of the next Ops meeting, can you add this to the agenda? The proposed principle has to be accepted in spirit by Ops before we deal with wording at Editorial. I think there's enough spelled out by Melissa to get it started.

**Comment by matentzn** [comment]
I think this "commitment to align with RO/COB" is a really great point, but can be quite a considerable effort. Have there been any attempts to properly enumerate the joys we would get from aligning with the two (I hope I know them all, but I expect we will need to have some airtight arguments to convince the 150 ontologies already in the OBO foundry)?

**Comment by matentzn** [comment]
I would like to re-surface this ticket here; I would suggest something like this (in addition to @mellybelly suggestions above):

### attribution should be standardised

I would like to suggest to _standardise the attribution of contribution_ as follows:

```
Assume scenario 1: Person X makes term request; person Y creates the term in the ontology.
```

1. whoever creates a term, uses the OBO prevalent `oboInOwl:created_by`  to make that clear using whatever system they want (maybe someone can comment whether they believe its worth standardising this towards the GO approach with three letter short cuts or whatever, I dont mind):

```
id: DEMO:001
created_by: Y
```

2. whoever creates the term add themselves and the NTR issuer as a _contributor to the term itself_. This is using dce:contributor (I know the dce:creator is used very frequently, but dce:contributor applies a bit more broadly), with a CURIE pointing to an ORCID (I kinda would have liked to use IRIs, but I have seen curies so often now, probably better to do that.) 

```
id: DEMO:001
created_by: Y
property_value: http://purl.org/dc/elements/1.1/contributor "ORCID:0000-0002-7356-ABCD" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor "ORCID:0000-0002-7356-WXYZ" xsd:string
```

A someone nicer variant of this could be:

```
id: DEMO:001
created_by: Y
property_value: http://purl.org/dc/elements/1.1/contributor "" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor "ORCID:0000-0002-7356-WXYZ" xsd:string
```


3. If the NTR issuer supplied a definition that can be used as the IAO:115 for that term, we can attribute them using the ominous xref syntax (along with a publication potentially) as follows:

```
id: DEMO:001
created_by: Y
definition: "Nice definition of my new term" [ORCID:0000-0002-7356-WXYZ, PMID:001]
property_value: http://purl.org/dc/elements/1.1/contributor "ORCID:0000-0002-7356-ABCD" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor "ORCID:0000-0002-7356-WXYZ" xsd:string
```

### After significant contribution, the contributors should be listed as ontology contributors

```
property_value: http://purl.org/dc/elements/1.1/contributor ORCID:0000-0002-7356-ABCD {name: "Jane Doe", institution: "EBI", funded_by: "somegrantnumber"}
```

Basically I suggest adding name, funding and institution info to make it easier to add attribution to institutions (and potentially grants). This could also be used for term level contribution.


### Ontologies should publish clearly visible summary stats on contributions as part of their release notes

If we standardise to the above, we can write a small ROBOT SPARQL pipeline to do that.

### pull requests should be merged after at most two weeks with no comments/reviews

I know this is largely unpopular, but I stand by this; we cant afford anymore to alienate potential contributors by having their pull requests, crafted with great effort, being ignored for months or even years.


Let me know whether you think this makes sense; dont worry too much about what you and your ontology have been doing so far and the effort involved to change to a standardised system; lets discuss what makes sense and then work out how to help people migrating to this system later; we have good tools to help with this kind of stuff, so lets not make "effort" the issue here.

**Comment by cmungall** [comment]
+1

cc @beckyjackson who is using ECO for definition provenance modeling

**Comment by nlharris** [comment]
I think most of this has been addressed since this ticket was created. How about if we close this as done, and @mellybelly or @sabrinatoro or other Governance Committee members can open new tickets with any items here that they feel still need to be completed?

**Comment by nlharris** [comment]
Closing as above; open new tickets if needed
