### ISSUE TITLE
broken links on legacy pages

### ISSUE THREAD

**Issue by zhengj2007** [OBOFoundry/OBOFoundry.github.io#117]
On page: http://obofoundry.github.io/legacy/participate.html
Join and Discussion link to file NOT found

Broken Links: 
http://obofoundry.github.io/legacy/coordination.html
http://obofoundry.github.io/publications.html

**Comment by cmungall** [comment]
Maybe we can just ditch legacy altogether?

**Comment by nlharris** [comment]
See also #25 
(I don't see how it could possibly be deemed URGENT to fix links in legacy pages!)

If there's an easy way to mark legacy pages as legacy (e.g. by putting it in the header) I think that would make this issue (even more) unimportant.

**Comment by nlharris** [comment]
I was going to say, "How would one even stumble upon the legacy pages?" but when I tried googling "Participate in the OBO Foundry" (not in quotes) the legacy page was the first hit! Maybe it's time to desupport the legacy pages and just have all URLs with /legacy/ redirect to the OBO Foundry home page? (It's apparently been five years since the legacy pages became legacy!)

I definitely would NOT be in favor of fixing links in legacy pages, though I do think it would be good (as i suggested above) to mark them as legacy (if we don't want to just hide them entirely).

**Comment by cmungall** [comment]
+1

**Comment by nlharris** [comment]
Closing this ticket, opened new one #1267 to redirect legacy pages.
