### ISSUE TITLE
Update review language on main OBO Foundry page

### ISSUE THREAD

**Issue by wdduncan** [OBOFoundry/OBOFoundry.github.io#1247]
On the main page we say in the blue block on top:
```
The processes of the Editorial working group are modelled on the journal refereeing process. 
```

We probably should update this, since it is in flux. My suggestion for now is to simply remove it.

**Comment by nlharris** [comment]
makes sense to me to just remove it for now.

**Comment by nlharris** [comment]
In my suggested text for the About page (which will mostly be based on the verbiage currently on the home page), I had already removed that text, as suggested by Bill.
Rather than do a PR to make this one change to the home page text, let's agree on the new, simpler home page content and the new About page--see #241. Proposed new text here: https://docs.google.com/document/d/1_XwrUSGx8aGBIZ6fPXGxpilyfJGIKAP01izAbVpFIcM/edit

**Comment by nlharris** [comment]
since #241 is done, i think this can be closed.
