### ISSUE TITLE
What taxon/tag to use for microbial ontologies?

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#136]
Currently the taxon field in the metadata is single-valued. 

What about microbial ontologies? Obvious 'microbe' is not monophyletic, and also a bit fuzzy. It is probably stretching the taxon field (even making it a union), so best done just with a tag.

What should this include?
- prokaryote (obviously)
- archaea (obviously)
- any single celled eukaryote? pombe, cerevisae?
- what about dicty, volvox? cc @pfey03
- viruses? E.g. https://en.wikipedia.org/wiki/Microbiology   - I would say restrict to cellular microbe
- nematodes? I think it simpler to exclude all animals, even 'microscopic' ones

I think the most straighforward is to use as a syn for prok | arch

**Comment by pfey03** [comment]
People working with dicty usually do not think of them as a Microbes. Do they all need to be bagged together?

**Comment by cmungall** [comment]
The use case here is that I want to be able to tag ontologies such as micro and omp with a taxon

I agree that classifying dicty as a microbe sounds odd. I think for the obo foundry microbe is synonymous with prokaryote? cc @carrineblank @mchibucos

**Comment by carrineblank** [comment]
Microbe is a colloquial term usually referring to a biological entity that is microscopic, and therefore doesn't correlate with a monophyletic group.  I would also recommend restrict to cellular organisms (not viruses).

For MicrO, our ontology refers to qualities, processes, and entities associated with the description of prokaryotic taxa (hence relating to the taxa Bacteria and Archaea, so these should be taxonomic tags for MicrO).

Prokaryote includes Bacteria and Archaea, so prok | arch (which I believe reads "prokaryote or archaea"?) would be redundant.

**Comment by cmungall** [comment]
Ah yes, I meant "Bacteria and Archaea"

OK, so it sounds like when OBOF ontologies say micriobial they mean Prok = Bacteria OR Archaea

So the ticket remains open for us OBO devs to accomodate a solution

 * allow multiple values with UnionOf semantics
 * use precoordinated non-monophyletic UnionOf classes e.g. from purl.obolibrary.org/obo/go/extensions/go-taxon-groupings.owl
 * not worry about taxonomic classification for microbial ontologies

**Comment by cmungall** [comment]
Ah yes, I meant "Bacteria and Archaea"

OK, so it sounds like when OBOF ontologies say micriobial they mean Prok = Bacteria OR Archaea

So the ticket remains open for us OBO devs to accomodate a solution

 * allow multiple values with UnionOf semantics
 * use precoordinated non-monophyletic UnionOf classes e.g. from purl.obolibrary.org/obo/go/extensions/go-taxon-groupings.owl
 * not worry about taxonomic classification for microbial ontologies

**Comment by carrineblank** [comment]
You should also talk to the OMP folks as well, since their usage of the term "microbial" might be larger than just prokaryote.

**Comment by mchibucos** [comment]
Thank you Chris and Carrine for looping me into the discussion. I agree with Carrine's statement that "Microbe is a colloquial term usually referring to a biological entity that is microscopic, and therefore doesn't correlate with a monophyletic group." We are in agreement that "prokaryote" includes both Bacteria and Archaea. However, at OMP we take the broader view of what comprises a "microbe", which is described by most Intro to Microbiology courses & textbooks as encompassing bacteria, archaea, fungi, protists (protozoans, unicellular algae, etc.), and viruses. (Admittedly viruses are outside the practical scope of OMP, however.)

We feel that "microbe" is not synonymous with prokaryotic. So if the goal is to apply taxon tags to specific ontologies, I am afraid that OMP would require several beyond Bacteria and Archaea or only "prokaryotic". At *present* our terms are mostly focused on phenotypic traits that are described in Bacteria, because we have started building the ontology using E. coli as a focus. However, we see no reason why OMP couldn't be used to annotate other "microbial" cells, such as those of the fungus Saccharomyces, for example. So ideally more than one taxon tag could be used for ontologies that encompass diverse areas of the tree of life...

**Comment by cmungall** [comment]
OK, good to know, and the reason I'm pushing is to try and determine 
areas of overlap. There are various yeast phenotype ontologies already 
in existence, such as FYPO (@mah11).

**Comment by carrineblank** [comment]
We should also include Ramona Walls in on this discussion, as she is working on her microbial environments ontology (MEOWL).

**Comment by jimhu-tamu** [comment]
Chris, we discussed collaboration with Val Wood at the GO consortium about integrating OMP and FYPO. We just wrote a letter of support for them.

**Comment by rlwalls2008** [comment]
Sorry to chime in late on this, but in brief I second what Markus said.
iMicrobe (and MEOWL) cover viruses as well.

Ramona

------------------------------------------------------
Ramona L. Walls, Ph.D.
Scientific Analyst, The iPlant Collaborative, University of Arizona
Research Associate, Bio5 Institute, University of Arizona
Laboratory Research Associate, New York Botanical Garden

**Comment by mchibucos** [comment]
Thanks Ramona. Regarding viruses, I must issue a correction: although we haven't done much in the way of describing viruses yet, viruses can also fall within the scope of OMP. I have modified my initial post to reflect this.

**Comment by mcourtot** [comment]
How do we currently use this tag: is it only for sorting/information?

If yes why not have a "multi-species" one for those cases in which there is
not a clear taxon? In the vast majority of cases we are able to assign a
specific tag, so we may end up with a few "multi-species" ones but
shouldn't be overwhelming.

**Comment by nlharris** [comment]
What's the status of this issue?
