### ISSUE TITLE
New ontology request for CDNO

### ISSUE THREAD

**Issue by LilyAndres** [OBOFoundry/OBOFoundry.github.io#1369]
## Ontology title
Crop Dietary Nutrition Ontology 

## Requested ID space
CDNO

## Ontology location
[https://github.com/Southern-Cross-Plant-Science/cdno](https://github.com/Southern-Cross-Plant-Science/cdno)

## Contact person
Name: Graham King
Email address: [graham.king@scu.edu.au](url)
GitHub username: CropStoreDb 

## Issue tracker
[https://github.com/Southern-Cross-Plant-Science/cdno/issues](https://github.com/Southern-Cross-Plant-Science/cdno/issues)

## Ontology license

- [x ] CC0 (public domain)
- [ ] CC-BY (version 3 or later)
- [ ] Other: *please specify*

## Available ontology formats
OWL

## What domain is the ontology intended to cover?
The Crop Dietary Nutrition Ontology provides structured terminologies to describe nutritional attributes of crop plants and their harvested materials that contribute to human diet. The common vocabulary and relationships defined within CDNO should facilitate description, communication and exchange of plant-derived nutritional composition datasets typically generated by analytical laboratories. The CDNO therefore supports characterisation of crop diversity and management of plant genetic resources, as well as sharing of knowledge relating to dietary composition between a wider set of researchers, breeders, farmers, processors and other stakeholders.

## Related OBO Foundry ontologies
CHEBI, ENVO, FoodOn, PATO, PO

## Intended use/related projects
These terms are intended primarily to be associated with datasets that quantify concentration of chemical nutritional components derived from plant samples. 

## Data source
Hand curated spreadsheet from [Azman Halimi et al., 2019](https://pubmed.ncbi.nlm.nih.gov/31756768/), informed by feedback from curators of Food Composition Databases/Tables including INFOODS, USDA Data Central, EuroFIR and CHEBI. 

## Additional comments or remarks
The OWL file for which the link is provided above is temporary and solely a place holder.
We have completed the preparation of 536 terms and their relationships according to classification of dietary nutrients, where over 300 are associated with CHEBI terms. 
The CDNO has been developed primarily by Liliana Andres and in consultation with and guided by Ramona Walls and Kai Blumberg, University of Arizona (ENVO). 
We have also benefitted from extensive discussions and input from Damion Dooley, University of British Columbia (FoodOn).

**Comment by ramonawalls** [comment]
CDNO curators have made considerable effort to reuse existing terms, including contributions to CheBI, ENVO, and FoodOn.

**Comment by matentzn** [comment]
Yes I agree a lot! Very clean set up re-using existing ontologies. Do I see this correctly that there are actually no terms defined in the CDNO namespace? Is there any axiomatisation in CDNO that does not come from other ontologies?

**Comment by kaiiam** [comment]
> Yes I agree a lot! Very clean set up re-using existing ontologies. Do I see this correctly that there are actually no terms defined in the CDNO namespace? Is there any axiomatisation in CDNO that does not come from other ontologies?

Thanks @matentzn for weighing in. In addition to importing from the above mentioned ontologies there are **new** terms that we are currently preparing that will be in the CDNO namespace. We should have them added to the CDNO-edit file soon. 

1. We're planning on hosting certain top-level nutritional terms such as `resistant starch` and `trans fatty acid`, but if you think those are better put in CHEBI then we could help add them there instead. 

2. The major focus (and bulk) of the new CDNO terms will be to represent the various sugar-like intermediate molecules determined via nutritional analytical laboratory methods. For example a laboratory will extract the `starch` from a plant like barley or rice, and measure the amount of `amylopectin` that is derived from the total starch fraction. 

In order to represent this concept, we'll create a new CDNO term: `amylopectin derived from starch`, which will have an equivalence axiom like: 

```
amylopectin and 'derives from' some starch
```

Where we import `amylopectin` and `starch` from CHEBI, and `derives from` from RO. There are quite a few of these derivative terms which were currently working into the ontology. We feel it would be better not to have these classes in CHEBI as they are specific to the analytical practices of certain research communities (sugarA derive from sugarB derived from sugarC etc), rather than being compounds that exist in nature. 

3. Finally we will have another set of `concentration` terms in the CDNO namespace. These terms will follow the existing `chemical concentration` DOSDP pattern established in [ENVO](https://github.com/EnvironmentOntology/envo/blob/master/src/envo/modules/chemical_concentration.csv) and [TO](https://github.com/Planteome/plant-trait-ontology/blob/master/patterns/composition/composition.tsv). 

Unlike the ENVO and TO concentration terms, which include in ENVO's case concentrations of CHEBI:`chemical entities` in ENVO:`environmental materials`, or TO's case concentrations of  CHEBI:`chemical entities` in PO:`plant structure`, the new CDNO concentration terms will be concentrations of the aforementioned CDNO: sugar derivative terms (e.g., `amylopectin derived from starch`) in in PO:`plant structure`.

I hope this helps to clarify the scope of CDNO. Thanks again for considering it for inclusion into OBO.

**Comment by LilyAndres** [comment]
Thanks @ramonawalls, @matentzn and @kaiiam. 

As @kaiiam describes in the examples, CDNO provides domain-specific categories/classification and relationships that represent efficient reuse of ChEBI for the dietary nutritional components. 

I also wanted to mention that, in addition to the class `'dietary nutritional component' [e.g CDNO: amylopectin and derives from starch]` and the class `'nutritional component concentration' [e.g. CDNO: concentration of CDNO: amylopectin and derives from starch]` we intend to create two more classes:

1) `CDNO: 'analytical methods'` which will reuse terms from OBI, CHMO and FIX such as `'high-performance liquid chromatography column' [CHMO:0000976]`

2) `CDNO: 'dietary function'` that will also reuse CHEBI terms such as `'Iron chelator' [CHEBI:38157]` and `'Inhibitors' [CHEBI:35222]` that are considered 'antinutritional factors', a term that will be defined in CDNO. 

However, these two classes `(CDNO: 'analytical methods' and CDNO: 'dietary function')` are still in the early-stage and require more work in classifying and structuring the concepts. 

So for now only the classes `'dietary nutritional component'` and  `'nutritional component concentration'` will be complete in the CDNO, and for the classes `CDNO: 'analytical methods' and CDNO: 'dietary function'`, only the examples described in this post will be integrated for now.

**Comment by ddooley** [comment]
Hello Liliana,
At moment at first glance some OBOFoundry folks were thinking that CDNO looked like an application ontology since it doesn't have any CDNO URI terms in it at moment, implying one wouldn't really need to load CDNO to reuse OBOFoundry terms.  As you note there are a few other broad terms like 'dietary function' in the pipe, though perhaps some others like 'analytical method' might have CHEBI curators interested.  

What I recall is that you have quite a number of precomposed crop organism nutritional content measure terms in the pipe. Is it possible to load those into the github CDNO to demonstrate the offering of reusable (MERIOT) terms for the Foundry?  Showing their axiom composition would be attractive too.

**Comment by kaiiam** [comment]
@ddooley like I said above there there we many of these precomposed crop organism nutritional content measure terms in the works. We'll try to get them into the ontology soon. @LilyAndres just wanted to get started with the registration process while we were pushing these. 

Is it a requirement to have our new terms in prior to registration, or can we work on both simultaneously?

**Comment by ddooley** [comment]
Hi Kai,
Thanks for reiterating that.  I think a parallel course would be ok if CDNO supplied a chunk of the new term labels here - @matentzn would that be enough to judge whether this treatment of the nutritional component subdomain stands on its own legs, in a similar way to ENVO's environmental compound measurements?

**Comment by LilyAndres** [comment]
Thanks @ddooley, @matentzn please have a look at the following list where I mention some examples of new terms that CDNO intends to provide, I hope this helps. 

Example of terms that will be defined in **'CDNO: dietary nutritional component'** class, we have around 500 terms
| Name | 
| ------------- | 
| dry matter |  
| available carbohydrate| 
| free sugar|  
| dietary fibre  | 
| soluble dietary fibre | 
| resistant starch  | 
| insoluble dietary fibre | 
| seed storage protein  | 
| plant secondary metabolite  | 
| inulin derived from fructan | 
| arabinoxylan derived from hemicellulose  | 
| xylan derived from hemicellulose | 
| starch is a available carbohydrate  | 


The terms from the class `CDNO: dietary nutritional component` derive around 500 terms to create pre-composed terms with PATO: 'concentration of' in the class:
**'CDNO: nutritional component concentration'** 
| Name | 
| ------------- | 
| concentration of inulin derived from fructan | 
| concentration of arabinoxylan derived from hemicellulose  | 
| concentration of xylan derived from hemicellulose | 
| concentration of rhamnogalacturonan derived from pectin | 

**'CDNO: dietary function'** class (early stage)
| Name | 
| ------------- | 
| antinutritional factor | 


**'CDNO: dietary function'** class (early stage)
 subclasses to be defined 

Thanks, please let me know what you think.

**Comment by kaiiam** [comment]
Thanks @LilyAndres just to be clear we won't be making a class `starch is a available carbohydrate` In our the nutritional framework provided by our collaborators, we'll have `available carbohydrate` as subclass to CHEBI:`carbohydrate` and we'll have classes like `starch` be subclass to `available carbohydrate`. 

This simplified view of CHEBI will make it easier for those in the food/nutrition sciences to more easily browse through CHEBI with only the classes they are expecting to find. Aka, we won't display all of CHEBI or BFO to them.

**Comment by LilyAndres** [comment]
Oh my, thanks @kaiiam, yes `'starch is a available carbohydrate'` shouldn't be there. Thanks!

**Comment by matentzn** [comment]
I will be honest: I trust @ddooley in particular since CDNO is so close to his own domain; if he believes that the scope of CDNO is general enough for the newly proposed terms, I am fine. I would generally encourage to push as many of the newly proposed terms into higher level reference ontologies such as chebi or foodon, and avoid as much as possible to adding terms to CDNO, unless they are so specialised that they really cant go anywhere else. 

I love the fact you are referencing TO and ENVO patterns! Great!

As for the rest, I will look at it again one more time. @kaiiam I know you have done it above, but just for clarity: could you describe to me one last time, other than the newly proposed terms you list, what other axioms are being added to CDNO? Is any axiomatisation introduced that affect entities that are _not_ in the CDNO namespace? So basically I am asking: what axioms, other than those containing CDNO terms, will be in the final product (or in another words, what would cdno-base.owl look like).

**Comment by kaiiam** [comment]
> I would generally encourage to push as many of the newly proposed terms into higher level reference ontologies such as chebi or foodon, and avoid as much as possible to adding terms to CDNO, unless they are so specialised that they really cant go anywhere else.

Yes we agree and @LilyAndres has been working to do so the terms which are in scope for CHEBI.


> Is any axiomatisation introduced that affect entities that are not in the CDNO namespace?

No. There are some annotation properties and perhaps some object properties identified in the course of this work that need to be added to existing CHEBI terms @LilyAndres has been doing this . 

> what would cdno-base.owl look like

As discussed with @LilyAndres the UNIQUE CDNO namespace terms which would be in ` cdno-base.owl` are as follows:

# 1) CDNO top level terms

These are terms which we think are in scope for CDNO, but please let us know if you think any are better put in CHEBI or elsewhere. 

Ontology ID | label | Notes:
-- | -- | --
CDNO:0000001 | dietary nutritional component | Top level term for our hierarchy containing a subset of chebi:chemical   entity  classes which are of interest to nutrition and plant scientists.
CDNO:0000002 | dry matter | Refers to plant material which is dried out for lab analysis, we'll make   it be subclass to ENVO:plant matter. With an axiom linking to pato:dry.
CDNO:0000016 | available carbohydrate | Subclass of chebi:carbohydrate working def: Carbohydrates which in   monogastric animals are absorbed in the small intestine and catabolized.
CDNO:0000021 | free sugar | Refers to monosaccharides and disaccharides which are part of foods or   food additives.
CDNO:0000025 | dietary fiber | Plant material which is resistant to enzymatic digestion. (e.g. Lignin).
CDNO:0000026 | soluble dietary fibre | subclass to dietary fiber, will link to PATO:soluble in.
CDNO:0000027 | resistant starch | Subclass to dietary fiber, includes starch compounds which resist   enzymatic digestion.
CDNO:0000050 | insoluble dietary fibre | Also subclass to dietary fiber, narrowing down on those which are non   soluble.
CDNO:0000068 | seed storage protein | Proteins that accumulate significantly in developing seeds. Can link to   PO:seed.
CDNO:0000075 or CHEBI:33259 | element | Subclass to (or use of) CHEBI:elemental molecular entity, which only   refers to those which are used by organisms  to perform functions   necessary for life.
CDNO:0000076 | macro element | subclass to CDNO:element or CHEBI:elemental molecular entity, which is   required in relatively large quantities for metabolism.
CDNO:0000077 | trace element | subclass to CDNO:element or CHEBI:elemental molecular entity, which is   required in relatively small quantities for metabolism.
CDNO:0000078 | plant secondary metabolite | CHEBI currently has metabolite and plant metabolite, but not secondary   metabolite or plant secondary metabolite. We'd work with CHEBI to place this   appropriately (CDNO or CHEBI).




# 2) Combinatorial sugar derivative terms

There are ~60 of these at the moment. These terms represent what people measure when doing lab sugar analyses. An example is as follows:

Ontology ID | label  | equivalence axiom | definition
-- | -- | -- | --
CDNO:0000018 | glucose derived from amylopectin derived from starch | (glucose and 'derives from' some 'amylopectin derived from starch') | Glucose which is derived from amylopectin derived from starch.

I can provide the entire list now if desired, I should have the robot template with all of these complied soon. 

# 3) CNDO concentration terms

In addition we will have our concentration quality terms crossing the above `sugar derivative terms` with PO:`plant structure` (following the ENVO/TO DOSDP structure). 


Ontology ID | label | equivalence axiom | definition
-- | -- | -- | --
CDNO:xxx | concentration of glucose derived from amylopectin derived from starch in   plant structure | concentration of'      and ('inheres in' some          ('glucose derived from   amylopectin derived from starch'          and ('part of' some 'plant   structure'))) | The concentration of glucose derived from amylopectin derived from starch   when measured in a plant structure.

# 4) Future directions

The use cases @LilyAndres and @CropStoreDb are working on will also require terms for `analytical method` and `dietary function`. 

For the former as @LilyAndres mentioned it would be ideal to use terms from OBI, CHMO and or FIX, so we'll try to work with them to add missing terms. 

For latter as far as we know there doesn't appear to be anything like `dietary function` in OBO currently. If there is please let us know we'd prefer to reuse then invent. However, if as we suspect there isn't, we can try to create some classes here, but if there's a more top level nutrition ontology we could always cede such a term there.

**Comment by matentzn** [comment]
Thank you very much, this is a great summary, and it answers all my questions. Unfortunately, the next operations committee meeting is 12th January - which is the forum in which I would present your case to the rest of the operations committee and give them a chance for Q&A. Is that on schedule for you? I think the main question would be about moving some CDNO terms to more higher-level ontologies. Else, I cannot see any issues at the moment.

**Comment by kaiiam** [comment]
No thank you @matentzn! @LilyAndres can speak to any timeframe requirements. Thanks for discussing this in the next obo ops call. We've made our pre-alpha release which you can now see in our [cdno-edit.owl](https://github.com/Southern-Cross-Plant-Science/cdno/blob/master/src/ontology/cdno-edit.owl) file. 

Loosely following from the examples of @jamesaoverton and @ddooley in OBI and Foodon, we'll be developing from robot templates and DOSDPs as source. You can find our google doc for our working templates [here](https://docs.google.com/spreadsheets/d/1vpQGsPDun5GG-b3_aKLjoItWW8Z4tKk1DIFe1Qx8zaw/edit?usp=sharing). Please let us know if you have any further questions for us.

**Comment by kaiiam** [comment]
Note on the  cdno-edit.owl file, all the classes are in the direct imports so you'd have to clone the repo to see it at the moment.

**Comment by LilyAndres** [comment]
Thank you so much @kaiiam for the summary and yes @matentzn that date works for us, also thank you so much for discussing the CDNO with the OBO team, looking forward for that discussion.

**Comment by nlharris** [comment]
@LilyAndres do you have the info for joining the call on Jan 12?

**Comment by LilyAndres** [comment]
@nlharris no, sorry. Could you please provide the details? Thanks a lot.

**Comment by matentzn** [comment]
Ah sorry all, I think my message was misunderstood- there is no need for anyone to join the OBO call apart from the commitee members! It's really about us discussing the case; I meant I would make sure you get your feedback around that date :P sorry for the misunderstanding

**Comment by LilyAndres** [comment]
That's what I thought :) no worries, thanks a lot.

**Comment by LilyAndres** [comment]
I think it is time to close this issue and move on to the release, the ontology just come out from the oven :)

**Comment by ramonawalls** [comment]
Congrat, Lili!

**Comment by jamesaoverton** [comment]
See #1425 and https://github.com/OBOFoundry/purl.obolibrary.org/pull/726
