### ISSUE TITLE
Add Aber-OWL generically or on a per-ontology basis?

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#144]
cc @leechuck 

Some browsers can be added automatically, e.g. ontobee, as they use consistent id/prefix

I don't think we can do this with aber-owl, e.g. what we call 'eo', aber-owl calls
http://aber-owl.net/ontology/PECO

(I would prefer eo is renamed to something more descriptive like peco but that's another issue)

We could still do a generic linkout if aber-owl provides us with a specific url, e.g. http://aber-owl.net/ontology/purl=<COMPLETE PURL>

But not sure if it grabs everything from OBO (it is either a superset or an overlapping set)

**Comment by leechuck** [comment]
That would be great. We now download all the OBO ontologies from their purl using the yaml file, once a day, and will add the http://aber-owl.net/ontology/purl=<purl> link in the next week; but we need to sort out some problems with inconsistent ontologies and unsatisfiable classes first, otherwise some ontologies in OBO will look very broken (e.g., FMA has >70k unsatisfiable classes which always show up in subclass queries, so we will switch to a structural reasoner for these ontologies).

**Comment by cmungall** [comment]
You may want to coordinate with @simonjupp, I believe he attaches a similar tag for similar reasons.

**Comment by simonjupp** [comment]
Yes, we have some properties in our config that will either use Hermit, ELK or the structural reasoner. By default all ontologies from obo foundry will be classified with ELK, but we had problems with a couple so I had to add an additional bit of config on our side that forces some to use the structural reasoner.

**Comment by leechuck** [comment]
We now provide access to all ontologies in the OBO library through http://aber-owl.net/ontology/purl=<purl>; alternatively, we also updated http://aber-owl.net/ontology/<prefix> to use the OBO prefixes in preference to BioPortal's (which resolves the "EO" issue which in BioPortal stands for the Ethnicity Ontology).
Inconsistent ontologies and ontologies with more than a few (>100) unsatisfiable classes also use a structural reasoner now so that AberOWL should be able to render all ontologies in the OBO library properly.
Please let me know if there is anything else we can do; it would be great to have links to the ontologies in AberOWL from the new OBO page.
