### ISSUE TITLE
Add OCLC entry for MicrO

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#147]
cc @carrineblank

Someone needs to add the usual entries for micro in purl.oclc.org. Can someone elee take care of this thanks. Note I think OCLC is still broken for adding new groups.

**Comment by mcourtot** [comment]
I created a PURl to have resolution of the main file, http://purl.obolibrary.org/obo/micro.owl. I haven't added a domain yet.

There are few issues:
- the file currently linked is https://raw.githubusercontent.com/carrineblank/MicrO/master/MicrOandImportModules/MicrO.Oct15.owl; it would be preferable to have a stable URI (i.e., not date based) so that the PURL always point to the latest version
- @carrineblank I do not have a PURL username for you so couldn't add you as maintainer
- the URI of terms in the file are problematic: 
1. http://www.semanticweb.org/geomicro/ontologies/2013/7/untitled-ontology-15#definition for APs
2. http://www.semanticweb.org/geomicro/ontologies/2013/7/untitled-ontology-15#MicrO_0000110 for terms

If desired we can help sort those out to conform to the ID policy at http://obofoundry.github.io/id-policy.html. This would allow terms to be resolved via Ontobee.

**Comment by rlwalls2008** [comment]
Can someone please create a YAML file for MicrO, so I can update the PURLs as I fix the MicrO IRIs?

 I could add the file by hand (which I am happy to do), but I suspect @jamesaoverton may have a script for generating them.

@carrineblank branched the MicrO repo and I am working on updating the IRIs. Will go over how I did it with you when it is ready, today or tomorrow.
