### ISSUE TITLE
Automatically regenerate derived files

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/OBOFoundry.github.io#1570]
The README explains that various merged artifacts must be periodically rebuilt and merged:

https://github.com/OBOFoundry/OBOFoundry.github.io#generation-of-downstream-artefacts

[Edit: You don't actually need Jekyll to regenerate the files.] Although @matentzn has had trouble getting the right Jekyll/Ruby version, I've found this process to be reliable: I check the results but never find major problems. If getting the right dependencies is a problem, we could use a Dockerfile #557.

As discussed in #1568, it would be nice to (at least try to) do this with GtHub Actions. Maybe after merging to `master`, or just when `ontology/*` has changed?

@cthoyt Do you want to take a crack at this?

**Comment by cthoyt** [comment]
I was actually just thinking about this and made a fork to see if I could get github to auto-generate this with GitHub Pages (https://cthoyt.com/OBOFoundry.github.io/) I think there are a lot of legacy configurations for old versions of jekyll that aren't compatible with the new kind. I think it would be quite nice for github to do most of the work for us, so I might take a crack at trying that first rather than reverse engineering the old stack

**Comment by jamesaoverton** [comment]
Some clarifications:

To regenerate the files you need Make, Python 3.6+, and `riot` which is from Apache Jena. Jena 3.7.0 works for me.

While you need Jekyll to run/test the site locally, you don't need it to regenerate the files. Jekyll 4.2.0 has been working for me. I forget exactly what problems Nico was having.

**Comment by matentzn** [comment]
My problem was that I didnt install the right ruby version; I had to install:

```
ruby2.6.6
jekyll-4.20
```

to get it to run!

**Comment by cthoyt** [comment]
yup I also had issues with ruby 2.6.0

**Comment by matentzn** [comment]
This has been solved for a while!
