### ISSUE TITLE
Clarifying FP7: RO re-use

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#1587]
We want to clarify what is meant by "there SHOULD still be coordination with RO, for example in the form of an issue submitted to the RO tracker." in http://obofoundry.org/principles/fp-007-relations.html

From the Sep 7 OFOC call: 
Add something like "Each OBO ontology MUST reuse existing relations (aka object properties) that have already been declared in the Relations Ontology (RO), rather than declaring duplicative relations. In some cases it may make sense for an ontology to declare a new relation in its own ID space. In these cases, *the new relation MUST be classified under an existing RO relation* and there SHOULD still be coordination with RO, for example in the form of an issue submitted to the RO tracker.

**Comment by cthoyt** [comment]
does this apply both to relations to other named entities and literals?

It always irked me that there aren't standard properties for InChi and SMILES, and several of the other relations/properties in ChEBI as well

**Comment by matentzn** [comment]
Good question.. not sure. My primary concern is object properties, but there really is know rational reason behind it.

**Comment by nataled** [comment]
Text added. More suggestions are in issue #1680. I think this issue can be closed (but not before a new issue is created for @cthoyt 's concern, if he so desires).

**Comment by cthoyt** [comment]
Thanks for the note @nataled, I just made a new issue for further discussion.

**Comment by alanruttenberg** [comment]
Hadn't noticed this language. The MUST is too strong. There's no guarantee that their is an appropriate superproperty unless RO includes topObjectProperty (which it can't). I think this needs to be a SHOULD, at best, with a comment addressing this.

**Comment by nataled** [comment]
@alanruttenberg would it help to add "if one exists" to the superproperty requirement and keep the MUST? I wasn't at the OFOC meeting where this was discussed so I'm relying on the notes captured above.

**Comment by alanruttenberg** [comment]
Something like that, yes. I reviewed the language and would propose the
following:

Each OBO ontology MUST reuse existing relations (aka object and data
properties) that have already been declared in the Relations Ontology (RO),
rather than declaring relations that mean the same as an existing RO
relation. Where it makes sense for an ontology to declare a new relation in
its own ID space and there is a RO relation that is logically a
super-property of the new relation, the new relation MUST be asserted to be
a sub-property of the RO relation. In such cases, it is requested that
there still be coordination with RO, for example in the form of an issue
submitted to the RO tracker.

Rationale for changes:
- I assumed that the scope of RO includes data properties so added that in
the parenthetical. If I've got that wrong, omit that.
- "duplicative" is jargon, so I rephrased to use more plain  language.
- The use of the term "classify" is something that is applied to classes. I
rewrote that bit to make it clear exactly what should be done.
- I felt the "in some cases" language was unnecessary and a bit off-putting.
- I objected to the MUST for coordination with RO, based on my past
experiences in trying to do so, so I reduced that to a polite request.

I wasn't sure whether the comma in "with RO, for example" should be moved
to the end "with RO for example,". Please check.

**Comment by alanruttenberg** [comment]
BTW, the page has empty sections "Examples, and Counter-Examples". If there
is nothing to say in a section then I think the section should be omitted.

**Comment by cmungall** [comment]
My proposed standard
https://github.com/chemkg/chemrof

e.g
https://w3id.org/chemrof/smiles_string

**Comment by nataled** [comment]
@cthoyt @cmungall please open a new issue to ensure that there's the proper follow-up.
