### ISSUE TITLE
Publicize social media links on web site?

### ISSUE THREAD

**Issue by nataled** [OBOFoundry/OBOFoundry.github.io#1682]
I see that the YAML files for a number of ontologies have, in addition to tracker specification, links to various types of social media (twitter, facebook, potentially others). These links are currently not displayed on the Foundry web site. I propose that:

1. There be a standardized way to indicate the links. For example, GO has:

<pre>
twitter: news4go
facebook: https://www.facebook.com/Gene-Ontology-305908656519/
</pre>

and at least DO does the same.

2. They get displayed.

**Comment by cthoyt** [comment]
Twitter seems to be rendered already, see https://obofoundry.org/ontology/go
<img width="1239" alt="Screen Shot 2021-12-14 at 12 33 52" src="https://user-images.githubusercontent.com/5069736/146050035-bd6aadf6-bc70-4846-9e02-947ae0359e09.png">


It appears this section of the ontology page template also allows for Google Plus (which doesn't exist anymore IIRC)

https://github.com/OBOFoundry/OBOFoundry.github.io/blob/6af82278956fa14cbafdc52727d008c1b615c6a9/_layouts/ontology_detail.html#L20-L30

**Comment by nataled** [comment]
Interesting. I'm looking at the GO page, and I do not see that twitter link. Using Firefox on a Windows 10 box, if that matters.

**Comment by jamesaoverton** [comment]
Like @nataled, I'm not seeing it either in Safari on iOS. It may be cross-site blocking on the `iframe`.

**Comment by cthoyt** [comment]
I followed the instructions at https://publish.twitter.com/# to make a new one for `@news4go`:

```
<a href="https://twitter.com/news4go?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-show-count="false">Follow @news4go</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```

**Comment by nataled** [comment]
@cthoyt so you're saying that these links already appear automatically--assuming the right browser is being used--when specified in the YAML file? If so, you should also be able to see that same button when viewing DO.

**Comment by jamesaoverton** [comment]
Thanks @cthoyt. I tried running this locally. That `a` element works. (Note that the `iframe` also works from localhost.) I think the `a` elements is better, but I would remove the `?ref_src=twsrc%5Etfw`. Then the template would be:

```
<a href="https://twitter.com/{{page.twitter}}" class="twitter-follow-button" data-show-count="false">Follow @{{page.twitter}}</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```

I'm not a Twitter user, so take this with a grain of salt, but I would find a link like <https://twitter.com/news4go> more useful, rather than a "follow" button.

**Comment by nataled** [comment]
Don't forget that this issue is for more than just twitter. ;)

**Comment by cthoyt** [comment]
> @cthoyt so you're saying that these links already appear automatically--assuming the right browser is being used--when specified in the YAML file? If so, you should also be able to see that same button when viewing DO.

Indeed this also works for DO, and I'll assume any other ontology that already annotates a twitter account (see screenshot I just took from firefox on my mac)
<img width="1277" alt="Screen Shot 2021-12-14 at 13 04 57" src="https://user-images.githubusercontent.com/5069736/146054807-048a4246-61a7-4166-bbc6-2f045bd58273.png">

@jamesaoverton good point - but twitter only generates follow boxes (which actually just link to the page) or mention boxes that create a new tweet when you navigate through it. The current configuration does what's expected.

@nataled I didn't forget this is more general, so I only referenced this issue from the PR instead of saying it closes it.

**Comment by cthoyt** [comment]
Follow-up question barrage for @nataled:

- besides GO, are there a meaningful number of facebook links?
- Are there any other social sites that would be worth putting?
- Does linking repos on GitHub fall under the umbrella of this issue (see #1688)?

**Comment by nataled** [comment]
@cthoyt I don't know the answers to any of these questions, unfortunately. I just happened to notice that there were links indicated in the YAML files when I was looking for an example of something completely unrelated and, realizing that these weren't visible (at least to me), thought it would be a good idea for them to be so. I haven't done a complete accounting of all possible social media links, nor checked to see how many ontologies use them. My thinking was that these were already 'canon' (so to speak) since they appeared in the YAML.

I wasn't thinking about GitHub repos since we already have visible links to trackers.

**Comment by matentzn** [comment]
I think a social link to "star a repo" would be nice.

In my opinion, no other social sites are used. 

@cthoyt let me know when you feel like this is ready for final review.

**Comment by nicolevasilevsky** [comment]
this ticket is too open-ended. We should open more specific, more targeted issues if needed.
