### ISSUE TITLE
Broken license icons on obofoundry.org

### ISSUE THREAD

**Issue by nlharris** [OBOFoundry/OBOFoundry.github.io#1773]
Some ontologies have less-common licenses that appear as broken icons (but with working hyperlinks) in the ontology table on obofoundry.org:
![Screen Shot 2022-01-26 at 2 13 15 PM](https://user-images.githubusercontent.com/348704/151256521-25f00428-71c2-48a9-a343-87419b48d2ac.png)

I'm not sure how easy this would be, but it would be good if the broken icons were replaced with the alt text.

**Comment by cthoyt** [comment]
I wouldn't suggest putting much effort into supporting the ontologies that do not use [FP-001](https://obofoundry.org/principles/fp-001-open.html)-compliant open licenses. Perhaps an alternative would be to put a warning that says for each of these ontologies that they do not use standard open licenses instead of an image/alt-text

**Comment by nlharris** [comment]
now fixed!
