### ISSUE TITLE
Create portals or pages for specific domains

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#19]
Many of our pages have a domain field. This is somewhat arbitrary but could be normalized.

It would be useful to have a page that lists all ontologies within a domain. Even better if this can be customized. For example, different community members could take responsibility for different domains: health, anatomy, environment, ...

**Comment by cmungall** [comment]
I have created a first pass at this.

Check out the branch in the PR and run jekyll and look at the example page:

http://127.0.0.1:4000/community/microbial.html

![image](https://user-images.githubusercontent.com/50745/48369690-2667e680-e66c-11e8-91e1-95792b58eaef.png)

**Comment by cmungall** [comment]
It would be cool to have browsers like OLS pick up the metadata here, and to allow browsing of groups of ontologies? @simonjupp 

TBD: how does the notion of a community overlap with the notion of a set of ontologies that are guaranteed to be mutually coherent, all inherit from obocore? @jamesaoverton

**Comment by jonquet** [comment]
Indeed, this is a cool feature. 
Which is why BioPortal and AgroPortal have this for a bunch of years with the group/category and slices mechanisms. 

An extract of https://dx.doi.org/10.1016/j.compag.2017.10.012 which give an updated description of the feature:

> Within AgroPortal, each time an ontology is uploaded into the portal, it is assigned a group and/or category. Groups associate ontologies from the same project or organization, for better identification of the provenance. We have created a group for each use case, except the fifth one that is not a source of ontologies, and another one for the OBO Foundry. For each group we have deployed a specific slice (a restriction of the user interface to a specific group of ontologies) as explained later. Categories indicate the topic(s) of the ontology, providing another way to classify ontologies in the portal independently from their groups or provenance. As of now we have defined 20 general categories such as Farms and Farming Systems, Plant Phenotypes and Traits, Plant Anatomy and Development, Agricultural Research, and Technology and Engineering. These categories were established in cooperation with FAO Agricultural Information Management Standards (AIMS), which has maintained the VEST Registry since 2011.
> 
> Groups and categories, along with other metadata, can be used on the “Browse” page of AgroPortal to filter out the list of ontologies (cf. Fig. 3). Of course, groups and categories are customizable, and will be adapted in the future to reflect the evolution of the portal’s content and community feedback. The portal’s architecture provides URIs for any portal objects, including groups and categories. For example, the URI http://data.agroportal.lirmm.fr/categories/FARMING identifies the group “Farms and Farming Systems.” External applications can use those URIs to organize ontologies or tag them.

For instance, the slice: 
http://obo-foundry.agroportal.lirmm.fr/ontologies
Shows the 21 ontologies in AgroPortal from the OBO Foundry.
The slice: 
http://crop.agroportal.lirmm.fr/ontologies
Shows all the ontologies from the Crop Ontology project.

Of course, the granularity of group/categories is customizable. BioPortal (@graybeal ) will have to update their classification to match the need. But they cover the whole OBO Foundry listing. 

In terms of metadata, groups and categories are identified by a field (group, hasDomain) on ontology description. For instance for ENVO see: 
http://data.agroportal.lirmm.fr/ontologies/ENVO?display_links=false&display_context=false

@cmungall If you assign a specific (new) metadata field in the Yaml descriptions to address this, then let us know. We (AgroPortal) will synchronize back our metadata.... I think BioPortal could do that too.

**Comment by nlharris** [comment]
Is @cmungall the only person who could do this?

**Comment by nlharris** [comment]
Maybe this is something @wdduncan could work on?

**Comment by jonquet** [comment]
If OBO Foundry needs custom groups/domains in AgroPortal let me know. 

I would recommend to sync up with @graybeal too see how BioPortal groups/domain can also handle new grouping suggestions if any.

**Comment by nlharris** [comment]
This is provided, more or less, by the option in the new home page to group and/or filter by domain, so can this be closed as done?
