### ISSUE TITLE
Edit button not working on publications.html

### ISSUE THREAD

**Issue by nlharris** [OBOFoundry/OBOFoundry.github.io#1925]
The edit button on https://obofoundry.org/registry/publications.html goes to
https://github.com/OBOFoundry/OBOFoundry.github.io/edit/master/docs/.md which is wrong

I'm not sure where/how these edit button URLs are generated.

**Comment by matentzn** [comment]
Actually, I made a mistake [here](https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1924)

Publications are automatically generated, and changes to the publication page need to be applied here:

https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/util/extract-publications.py

It looks a bit more scary, but I think you can figure it out.

The real issue here is fixed in https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1931 by removing the edit button when the page does not have an id (which in turn means it cant be edited).
