### ISSUE TITLE
Add a check that the id field is correct

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#196]
The id field should match the basename of the file, and should be all lowercase. The python scripts should check for this

**Comment by nlharris** [comment]
There's got to be someone other than @cmungall who could do this?

**Comment by jamesaoverton** [comment]
I think the dashboard effectively does this check, right @beckyjackson ?

**Comment by beckyjackson** [comment]
We have the `id.json` schema that checks that the ID is lowercase. We also have the `products.json` schema, but that doesn't look at the ID field at all.

I don't think the dashboard *actually* looks at the ID vs. the file name because it just uses the ID to download the file. If the ID doesn't match the file, then nothing can be downloaded.

**Comment by jamesaoverton** [comment]
If no registry entry can be downloaded, then the dashboard tests will fail. I think that's enough of a check.
