### ISSUE TITLE
Some ontologies have duplicate short and long descriptions

### ISSUE THREAD

**Issue by cthoyt** [OBOFoundry/OBOFoundry.github.io#1965]
The frontmatter can include a `description` field. 16 ontologies in OBO Foundry contain exactly the same text in the `description` field as the long-form markdown that follows the frontmatter. Potentially more contain text that's trivially different. We should do two things:

1. Remove the long-form text that duplicates the short-form text
2. Provide a test to make sure this doesn't happen again

**Comment by matentzn** [comment]
These two fields have different purposes on the website, but I agree, there is no point to render the same thing twice, see here:

https://obofoundry.org/ontology/aism.html

Good effort!

Just one thing about SOP moving forward - this does not count exactly as a mass change, but I think it would be a good idea to get some feedback on issues before tagging more than 5 people to review it. In the first instance, the Technical Working Group should agree with a change to the metadata, then we can put it forward to the community. I know it "slows you down", but I think its a better process - because asking people to interact cost "social capital", which we don't have much off.. :)

**Comment by nlharris** [comment]
See proposal from @cmungall in #1968

**Comment by lschriml** [comment]
If the two descriptions are exactly the same, then I agree we can remove the long term text.
If the two differ, even trivially, then they should remain. 
It should be up to the ontology developers to decide how their ontologies are described.
Lynn
