### ISSUE TITLE
PR tracker is still sourceforge

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#20]
Is this correct?

**Comment by lschriml** [comment]
Is this ticket referring to Public Relations for the OBO Foundry ? 
http://obofoundry.org/registry/publications.html

**Comment by cmungall** [comment]
This pertains to PRO

**Comment by nataled** [comment]
@cmungall I'm trying to do the migration (finally). It worked for only four issues, then quit (via "die") because an issue was assigned to someone not in the collab file. I then fixed that problem and ran again. The script successfully ran, but nonetheless seems to have stopped at about the same point. Maybe the already-existing issues on github blocked it somehow? Anyway, I now have several duplicated issues. I'm afraid to run it again.

**Comment by nataled** [comment]
Switch has been made. Issues ported to GitHub and SourceForge tracker has been disabled.
