### ISSUE TITLE
Documentation for Chairing OFOC call

### ISSUE THREAD

**Issue by shawntanzk** [OBOFoundry/OBOFoundry.github.io#2043]
We need documentation on chairing calls, @matentzn wrote the following: 

# How to prepare an OBO Ops call :
## Before the call:
1. Prepare a stub in the OBO Ops running agenda with all the regular items (you will find instructions in the running minutes itself). This include items like discussing new ontology requests, adding new members to the mailing list if any, etc.
1. Looking at OFOC call at OBO foundry repo. Pick one or two open issues you deem important and put them towards the end of the agenda. It is good to have these there. (This time, the main issue of importance is contuing our reviewer SOP).
1. Send an email to obo-operations (not obo-discuss!) to say: “I am doing this weeks meeting, here is a provisional agenda, feel free to add stuff!”
## During the call:
1. Wait for 8-10 people to arrive. Start the latest 4-5 minutes after the hour regardless of how many people are present.
1. Share your screen, say “hello y’all” and drive through the agenda. (You dont have to show your face, but some people do. This is up to you).
1. The important thing is to keep on track. If a discussion takes too long (in the sense of, you wont finish the rest of the agenda), you politely summarise the discussion and say: “After the meeting I will make an issue or a comment on the issue with the next steps”. We dont have to finish everything in a given sitting. If you are unsure: “Unfortunately we need to move on now, can I ask X (primary participant in the discussion) to summarise what needs to happen next, so we can move to the next item of the agenda?“.
1. Try to add a few raw notes to the agenda, capturing decisions etc. Do not hesitate to have people waiting for you taking notes: if we dont take notes with decisions, the discussion will resurface which means, more time will be lost.
1. Close exactly on the hour or earlier, no later, interrupt if necessary. Otherwise people will be forced to hop off in an impolite manner, which is not nice. Say thank you to the participants.
## After the call:
1. Sift through the agenda, streamline/format it a bit if it helps with clarity, make sure all issues are made on GitHub, all comments are made as discussed.

**Comment by nataled** [comment]
The pull request is https://github.com/OBOFoundry/OBOFoundry.github.io/pull/2074.

@cstoeckert note that I had to change the section headers from using three hash marks to using two so that the subsection headers displayed a reasonable size. You might have to make the corresponding change to your branch for consistency.

**Comment by nataled** [comment]
It is the intention of the EWG that the instructions for meeting chairs that is currently given in the rolling agenda document be replaced with a link to this SOP so that only one set of instructions needs revision, if necessary.

It is also the opinion of the EWG that the SOP document might need to be modularized in the future (that is, each SOP be given a dedicated .md file, and this file (SOP.md) act simply as a place for links to those other documents.

**Comment by nlharris** [comment]
Those comments seem reasonable to me. The first one (replace instructions in agenda doc with link to this SOP) could be done now as a PR.

Is there anything left in this issue that needs to be discussed, or can it be closed?
