### ISSUE TITLE
Bug: menus don't work from some pages

### ISSUE THREAD

**Issue by nlharris** [OBOFoundry/OBOFoundry.github.io#2088]
I'm not sure if this is a new bug, but I just noticed it.

From the home page, all the menus in the top bar work, but if you go to some pages, the pulldown menus stop working. ("Resources", which is just a pointer to a single URL, still works.)

For example, from https://obofoundry.org/about-OBO-Foundry.html the menus work, but from https://obofoundry.org/faq/index.html they don't (all top-level menu items just go to https://obofoundry.org/faq/index.html#, and the pulldown menus don't pull down). Other pages where the menu is broken include https://obofoundry.org/principles/fp-000-summary.html# and https://obofoundry.org/docs/SOP.html. Another page where the menu works is https://obofoundry.org/resources

**Comment by nlharris** [comment]
IMO, this is an unfortunate bug to have when we're about to give talks at ICBO to try to get people interested in the OBO Foundry. Is there someone who might be able to take a look?

**Comment by erik-whiting** [comment]
@nlharris I took a stab at this a couple of days ago and got some weird results. I reproduced what you described in the comment on the live website, but when I ran it locally, I could not reproduce it. That is, when I launched jekyll on my own computer and clicked the menus that you described, they dropped down as expected 😩 

I did notice one common trait among the pages in which the drop down menus don't work: they're all `.html` pages inside of subdirectories. For example the menus on the page `https://obofoundry.org/about-OBO-Foundry.html` work and this page follows the pattern `main_site/some_page.html` but it doesn't work on `https://obofoundry.org/docs/SOP.html` or any other page that follows the pattern `main_site/subdirectory/some_page.html`. This leads me to believe that some html or css file is being referenced incorrectly. Like, somewhere there's a `include ./file` when it should be `include ../file` or something like that. I don't know though, this is just conjecture. Still weird that it works locally.

I'm hoping the information above helps anyone who comes by this and decides to take a look. I'll take another shot at it this weekend unless you're presenting at ICBO tomorrow, in which case I can try to look at it tonight.

**Comment by nlharris** [comment]
@erik-whiting thanks for looking into it, and for noting the pattern among pages where the menus do vs don't work! Your theory sounds plausible, but it's going to be hard to track that down and if it can't be tested locally, that's going to make it hard to fix.

ICBO starts on Monday.

**Comment by erik-whiting** [comment]
Update on this bug:

This is happening because on the affected pages, Jekyll cannot find `all.js`. See this console error:
![image](https://user-images.githubusercontent.com/47164199/191905115-edb0c896-8f9f-4159-92bd-ea9f2956ae35.png)

Like I mentioned before, I think this is a path-referencing issue. Also, in regards to what I said earlier about how my local environment wasn't having the bug, I checked a diff between a file served on my environment and one served on the foundry webpage. Check it out:
```html
Me : <script src="/js/all.js"
OBO: <script src="js/all.js"
```
So for some reason, my Jekyll server is figuring out where `all.js` is while the one running on OBOFoundry isn't. The only thing I can think of now is that I'm using 4.2.2 and according to your `docker-compose.yml`, you're running 4.2.0. I'm going to see if the version is to blame.

...

Ok so I served the site locally with Jekyll 4.2.0 to see if I could reproduce the problem, but I can't. The only thing I can think of now is to dig into how Jekyll looks for JavaScript files and then use its syntax in `_includes/themes/bootstrap-3/default.html` file on line 112. Short of that, I'm pretty much out of ideas. I will do that later though as it's currently 2am and I have work in a few hours. I'll keep you posted!

**Comment by nlharris** [comment]
Excellent detective work, @erik-whiting! Thank you!

**Comment by erik-whiting** [comment]
I think #2097 will fix this 😬

**Comment by erik-whiting** [comment]
the pr definitely did not work 😭 sorry for wasting y'all's time again

**Comment by matentzn** [comment]
No worries at all :) We said we would try, what you proposed seemed to make some sense :) Unfortunately we don't have any front end developers in OBO, so we need to trial and error a bit. Do you want to try again / create an undo request?

**Comment by erik-whiting** [comment]
> No worries at all :) We said we would try, what you proposed seemed to make some sense :) Unfortunately we don't have any front end developers in OBO, so we need to trial and error a bit. Do you want to try again / create an undo request?

I will try again, in the meantime, here's a revert PR: https://github.com/OBOFoundry/OBOFoundry.github.io/pull/2098

**Comment by erik-whiting** [comment]
I took another shot at it, hopefully it works before you start presenting tomorrow 😬

**Comment by matentzn** [comment]
@erik-whiting 1,000,000 THANKS for fixing this just in time for ICBO! Without contributions like yours it would be hard to run anything! :) Thank you! 🙏

**Comment by nlharris** [comment]
@erik-whiting you are a star! Thanks so much for putting so much time and effort into it, and it's so great that you ultimately succeeded! Way to go! :star2:
