### ISSUE TITLE
Reviving obsolete, orphaned, or inactive ontologies should require careful re-evaluation

### ISSUE THREAD

**Issue by cthoyt** [OBOFoundry/OBOFoundry.github.io#2120]
We're looking at VariO, where the responsible person has got in touch and said that they have made a new release. However, the ontology does not follow the modern OBO principles. 

I think that all ontologies that have gone dormant and marked as either obsolete, orphaned, or inactive should have a very careful evaluation if they want to be marked as active, which should go much further beyond just the unit tests and metadata checks, but also a new, careful review.

**Comment by balhoff** [comment]
As discussed in a prior OBO operations meeting, we should at least require passing the dashboard for reactivation.

**Comment by matentzn** [comment]
## Vote

Ontologies that are moved non-active to active should be re-reviewed as if they are new ontology requests?

- 👍 Only ontologies that were previously marked `obsolete` must undergo the entire New Ontology Request review process again when set to `active`. Any other status changes do not automatically trigger a new review.
- 👎 Ontologies that change their status to active should only be required to pass the dashboard, not undergo formal re-review.
- 👀 Any ontology that was previously not set to `active` must undergo the entire New Ontology Request review process again when set to `active`.

**Comment by nlharris** [comment]
I am having trouble differentiating between these three options, as it seems like maybe they overlap. Like, if I think an orphaned -> active ontology should only be required to pass the dashboard, but an obsolete -> active one should require a NOR review, would I do both 👍 and 👎?

**Comment by matentzn** [comment]
@nlharris that is the first option, it's already been decided that no matter what, a status change will need a dashboard pass, see Jims comment above.

**Comment by nlharris** [comment]
That is a lot of process, but I agree that it seems ok, we can try it and see how it works.

In #4, "Review" should be "reviewer".

**Comment by matentzn** [comment]
@nlharris I lost track of what still needs to happen here. Can you summarise action items?

**Comment by nlharris** [comment]
I'm not quite sure. I think maybe we need to review this on an OFOC call to make sure there's agreement (or do we already have agreement?), and then we can add an SOP (with the 5 steps you listed above) to obofoundry.org, and add that to the list of SOPs in https://obofoundry.org/docs/SOP.html?

**Comment by matentzn** [comment]
I think its best to just make the PR first, and circulate that to OFOC people for review - these open debates do not often lead to clean and crisp action items..

**Comment by nlharris** [comment]
I see your point, though I find it a bit annoying when I make a PR and then people tear it apart and it's much more annoying to edit the PR than it would have been to get their input at the beginning.

Anyway, sure, I'll make the PR.

**Comment by matentzn** [comment]
Isn't it much easier now with suggestion mode? I don't think we should do the annoying thing just because I suggest it - what is the better way? I have rarely seen people actually contributing to discussions on tickets, so I thought (and maybe I am wrong) that the looming danger of a pending merge gets peoples attention more :)

**Comment by nlharris** [comment]
It's *somewhat* easier now with suggestion mode. :-)

Looking at your SOP above, is it intended to apply to changes in either direction (active -> obsolete/orphaned/inactive, or vice versa)? The title of this issue is just about reviving inactive etc. ontologies but I think your SOP applies in both directions. Just wanted to check that with you before proceeding.

If that's correct, then should we add anything explicit about ontologies needing to pass the Dashboard to be revived? That is implicit in "analyse the evidence for the change", so maybe we don't need to add that, but it could help avoid later back-and-forth if the owner of an inactive ontology seeks to have it revived when it's failing the Dashboard.

**Comment by matentzn** [comment]
This issue here is purely about going from obsolete/orphaned/inactive to active. The other way around already has a very clear SOP.
