### ISSUE TITLE
Proposal for a new `activity_status`: probationary

### ISSUE THREAD

**Issue by cthoyt** [OBOFoundry/OBOFoundry.github.io#2121]
The VariO issue that spawned several issues and PRs (#2103, #2090, #2118, #2120) seems to point to a totally new category of ontology outside of:
- active
- inactive
- orphaned
- obsolete.

This ontology has gone from being orphaned to being active, but does not (yet) adhere to OBO principles and standards. Therefore it's not appropriate to call it active, but I think something like "probationary" makes sense - showing it is active but does not yet qualify for OBO Foundry status.

The same could potentially be done for ontologies that are already in the OBO Foundry but blatantly do not follow required OBO Foundry guidelines, such as principles related to responsiveness (e.g., related to responsiveness on issue trackers), licensing (e.g., using inadequately open licenses), etc.

**Comment by zhengj2007** [comment]
Discussed on OBO operation committee meeting on 2022-10-04. We don't need to add a new activity_status. 
For any existing OBO ontology wants to change the activity_status from inactive or orphaned to active, it needs to pass dashboard checking.

@matentzn may help on add the ontology in the new ontology dashboard checking.

**Comment by nataled** [comment]
> For any existing OBO ontology wants to change the activity_status from inactive or orphaned to active, it needs to pass dashboard checking.

I think this is a good idea, but do we have it documented anywhere? If not (I can't recall if it is), we should add this.

**Comment by matentzn** [comment]
@nataled this is new. We would have to add it to https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/SOP.md

**Comment by matentzn** [comment]
In order to run an existing OBO ontology, in the dashboard, the only thing that needs doing is add a single line to the OBO NOR dashboard:

https://github.com/OBOFoundry/obo-nor.github.io/blob/master/dashboard-config.yml#L35

No need to provide metadata, because by default, metadata is obtained from the OBO registry.

vario, for example, is in pretty bad shape: https://obofoundry.org/obo-nor.github.io/dashboard/vario/dashboard.html

**Comment by cthoyt** [comment]
> Discussed on OBO operation committee meeting on 2022-10-04. We don't need to add a new activity_status. For any existing OBO ontology wants to change the activity_status from inactive or orphaned to active, it needs to pass dashboard checking.

I wish there were a more detailed explanation, to me this just sounds like a "no" but does not really address any of the points I made. Can somebody please elaborate on the discussion? Why did the discussion not take place on this thread instead? Should we point to this in future discussions of why it would be good to make OBO operations committee meetings more open, so this can be more transparent?

What happens when an ontology is marked as orphan but then has enough metadata to not be appropriate for orphan anymore, but doesn't pass the OBO dashboard? It's not active, but inactive is now not an appropriate status either.

**Comment by matentzn** [comment]
Can someone please take responsibility for creating a open obo-public google drive and create a new set of meeting minutes in there? All these should be made public. And I agree, this issue here needs to be explained better. I wasn't there for much of that discussion but I guess it goes something like this:


1. Adding a new status should be very well justified 
2. Instead of giving anyone probation period We just have them re-apply with the sole requirement of having to pass dashboard. If it passes dashboard, it's proof someone is looking after the ontology and can be set to active.

However, I think we can revisit this issue later when we have a proper technical framework to assess all OBO ontologies continuously. We need a status then like "pristine" or "godly" denoting ontologies which pass _all_ checks. Including COB and base consistency..

**Comment by nataled** [comment]
@cthoyt the discussion took place during the Ops meeting because this issue was tagged for discussion there. As for elaboration, from memory:
1) Several people expressed a desire to keep the tags simple, and not add more. So, yes, the outcome was 'no', as you surmised.
2) It was felt that a new status was not needed if we do as the final decision indicated: only list as active those previously orphaned or inactive ontologies that pass the checks. This is not too different from how NORs are handled.
3) Quite a few ontologies listed in the Library come from a time when listing was not gate-kept. Vario is definitely one of those. At that time, the gate keeping was in granting Foundry (as opposed to Library) status. (In fact, I can think of only one ontology that ever got rejected in those days, for being outside the scope of what the Foundry covers). 

My own general comments:
1) Meeting minutes will almost never cover a full discussion. IMO this is a good thing, as there is often rehashing, minutiae, and other things of little importance to capture.
2) Even those who have access to minutes very often miss what *is* captured.

**Comment by balhoff** [comment]
Closing this, since the decision was made not to add a new probationary status.

**Comment by cthoyt** [comment]
@balhoff Are there alternative ideas on what to call ontologies in the situation like VariO?
