### ISSUE TITLE
Compact URIs and source versions

### ISSUE THREAD

**Issue by rodrigobarnes** [OBOFoundry/OBOFoundry.github.io#230]
hi

I'm not expert in this area but reading the guidelines on citation at
https://github.com/OBOFoundry/OBOFoundry.github.io/blob/citation/docs/citation.md I wanted to test something.

For data integration and reproducibility, I think a Compact URI should include the source-provided version i.e.`/UBERON/2016-01-26/0000948` or similar is more informative than `UBERON:0000948` at little additional cost and reduces the need for the purl infrastructure. The compact URI could be appended to any service provider or a canonical purl endpoint.

Obviously, concepts and terms drop out of use and in some cases are reused so keeping version information is verbose but reduces error. 

Perhaps there's a way to cite a concept where the default version is implicitly 'latest' as in `/UBERON/-/0000948`. For backward compatibility, maybe the version could be added as a suffix to `UBERON:0000948` e.g. `UBERON:0000948:2016-01-26` and if missing would be interpreted as latest. Seems a bit ugly to use suffix.

There is some handling of versions in the payload of reference lookups, but there is a lot of value in having a standalone text that can be stored in traditional tabular storage.

Thanks for considering this

Rodrigo

**Comment by jamesaoverton** [comment]
Hi @rodrigobarnes, thanks for sharing your thoughts on this.

Just to be clear: the draft citation guidelines you linked to have not yet been reviewed or approved.

I've also given this topic some thought over the years. Currently our ontology releases are versioned but our terms are not. In order to specify a version of a term, you have to provide both the ontology version IRI and the term IRI.

I agree that it would be good to have a simple way to refer to the specific version of a term. However there's a number of important factors to consider. Here are two:

**Identity:** How do we know when are two ontology terms the same? Currently we compare the IRIs: same IRI, same term. Although terms may change over time, our practise is to keep the same IRI as long as we're improving or clarifying the term. I recognize that this can be problematic, but the key advantage is that we can compare two data sets that have been annotated with two different versions of the same ontology, because the term IRIs will be the same in both cases.

If a term had different version IRIs, we would need another mechanism for establishing identity of the term across time. This would need to work for annotated data, legacy data, internal ontology axioms, and external ontology axioms (i.e. reuse by other ontologies).

**Infrastructure:** Our term IRIs resolve to web pages on term browsers such as Ontobee and OLS. Those systems would have to support multiple versions of our ontologies. Since many of our ontologies are large and release frequently, this would be a major undertaking.

Neither of these is insurmountable, and I'm interested in working toward solutions, but I haven't been able to think of any that are simple and easy.

All software versioning and package management systems struggle with the identity problem. Some, like Maven, expect you to be explicit about the version of each dependency. Our system might be more like Python/Pip, where you specify dependencies without versions (`setup.py`), but can also "freeze" a set of dependencies with a specific versions for your local use (`requirements.txt`). There's a spectrum of other possibilities.

Note that things like functions and constants aren't independently versioned. Are our ontologies like packages and our terms like functions/constants? Maybe that analogy breaks down too quickly to be useful.

**Comment by nlharris** [comment]
what's the status of this?

**Comment by matentzn** [comment]
I think this has to be solved with metadata, not on term level. The IRI is timeless; the axioms and annotations surrounding the term could be in flow. They are versioned by context (ontology version IRI), but we are contemplating adding version information on the terms as well - although this has significant pushback from the community. I thin versining the identifiers themselves is currently infeasible, and IMO not desireable. I will close this for inactivity, but if anyone feel this needs more consideration, please reopen.
