### ISSUE TITLE
Bug in display of newsletter

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#2389]
@erik-whiting 

I merged https://github.com/OBOFoundry/OBOFoundry.github.io/commit/134993974a0abca719b5a830f4be9e5286b7ea9e

But it neither
- led to the menu showing the "Newsletter" section
- Nor any other viewable link of the newsletter

Can you figure out how to display this newsletter on the "blog" roll as @cthoyt called it?

**Comment by erik-whiting** [comment]
@matentzn some notes from my initial investigation:
1. You called the menu item "Citation." That's why you don't see "Newsletter"
2. It doesn't look like anything in the `_posts` directory is linked anywhere in the repo. In fact, doing a global search of the repo for "/posts" only yields one result, the one you added.

I'm working on fixing this, but the point is: it doesn't seem like posts has ever even been used, so no one noticed it wasn't working. Or it was used, but discontinued so long ago, that it stopped working at some point.

**Comment by erik-whiting** [comment]
Figured out the problem, see https://github.com/OBOFoundry/OBOFoundry.github.io/pull/2390

**Comment by cthoyt** [comment]
I can fix this later this weekend if Eric didn’t already

**Comment by erik-whiting** [comment]
> I can fix this later this weekend if Erik didn’t already 

I fixed it, see https://github.com/OBOFoundry/OBOFoundry.github.io/pull/2390

**Comment by matentzn** [comment]
This definetly works: https://obofoundry.org/posts/2023-06-16-InauguralNewsletter.html

But I am assuming not in the way @cthoyt was envisioning the "jekyll blog roll".. In any case, it shows up for now, so I am happy :) Thanks a ton @erik-whiting

**Comment by erik-whiting** [comment]
I didn't realize that's what you wanted, can you link me to the conversation where this was discussed so I can see what's being requested?

**Comment by matentzn** [comment]
No worries you couldnt have seen this: https://github.com/OBOFoundry/OBOFoundry.github.io/pull/2388#issuecomment-1593113574
