### ISSUE TITLE
Urgent: Fix master branch

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#2398]
Something in the testing pipeline changed, which causes new Pull Requests to fail. The master branch is still green, but the truth is that its failing due to changes in the testing dependencies themselves.

We need to:

- Know why it is failing
- How we can prevent it failing moving forward
- Fix it

@erik-whiting I assigned you but I am not sure if you are @deepakunni3 are responsible for the ontology metadata _testing suite_.

**Comment by deepakunni3** [comment]
I think this is in scope of the metadata registry steward.

Quick assessment from my side:

### Why tests are failing

The tests are failing because of Pydantic 2.0 (which was released last week).

When we define and use pydantic classes, the default behavior of pydantic has become more strict w.r.t. the typing of optional fields. Thus, you see validation errors when trying to work with pydantic classes that have optional fields but these optional fields weren't mark as `None` in the class itself. See https://docs.pydantic.dev/latest/usage/models/#required-fields for more information on this.

The quickest fix is to stick to pydantic 1.x

Alternatively, we can update the pydantic classes (and its usage) such that the validation errors are resolved.

### How to prevent it failing

I would recommend locking our dependencies in requirements.txt so that we can avoid scenarios where a newly released packages end up causing build and test failures.

**Comment by deepakunni3** [comment]
Working on a fix for this... stay tuned

**Comment by matentzn** [comment]
Excellent @deepakunni3 thank you! I am happy with your suggestion to freeze dependencies, but I could suggest to do something like https://github.com/INCATools/ontology-development-kit/blob/master/.github/workflows/constraints.yml which is an action that tries to automatically update constraints periodically.

**Comment by deepakunni3** [comment]
I like the idea of using actions to update the requirements.txt 👍

**Comment by nlharris** [comment]
Is this still urgent?
