### ISSUE TITLE
Request for new ontology [carolio]

### ISSUE THREAD

**Issue by samie3000** [OBOFoundry/OBOFoundry.github.io#2406]
### Title

Caroli's Disease and Syndrome

### Short Description

Ontology for Symptoms, Outcomes, and Treatment of Caroli's Disease and Syndrome

### Description

We aim to present CaroliO, an ontology for Caroli's disease and syndrome, which increases the potentials of enhancing diagnosis and treatment of these rare liver conditions.

### Identifier Space

CaroliO

### License

CC-BY 4.0

### Domain

biological systems

### Source Code Repository

https://github.com/TootooniLab/CaroliO

### Homepage

https://github.com/TootooniLab/CaroliO

### Issue Tracker

https://github.com/TootooniLab/CaroliO/issues

### Contribution Guidelines

https://github.com/TootooniLab/CaroliO

### Ontology Download Link

https://github.com/TootooniLab/CaroliO

### Contact Name

Mohammad Samie Tootooni

### Contact Email

mtootooni@luc.edu

### Contact GitHub Username

samie3000

### Contact ORCID Identifier

0000-0001-7235-4914

### Formats

- [X] OWL RDF/XML (.owl)
- [ ] OBO (.obo)
- [ ] OBO Graph JSON (.json)

### Dependencies

- doid
- symp
- RO

### OBO Foundry Pre-registration Checklist

- [X] I have read and understood [the registration process instructions](http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html) and the [registration checklist](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/RegistrationChecklist.md).
- [x] There is no other ontology in the OBO Foundry which would be an appropriate place for my terms. If there were, I have contacted the editors, and we decided in mutual agreement that a separate ontology is more appropriate.
- [x] My ontology has a specific release file with a version IRI and a `dc:license` annotation, serialised in RDF/XML.
- [x] I understand that term definitions, while not mandatory, are key to understanding the intentions of a term especially when the ontology is used in curation. I made sure that a reasonable majority of terms in my ontology have definitions, using the [IAO:0000115](https://ontobee.org/ontology/IAO?iri=http://purl.obolibrary.org/obo/IAO_0000115) property.
- [x] For every term in my ontology, I checked whether another OBO Foundry ontology has one with the same meaning. If so, I re-used that term directly (not by cross-reference, by directly using the IRI).
- [x] For all relationship properties (Object and Data Property), I checked whether [the Relation Ontology (RO)](https://ontobee.org/ontology/catalog/RO?iri=http://www.w3.org/2002/07/owl%23ObjectProperty) includes an appropriate one. I understand that aligning with RO is an essential part of the overall alignment between OBO ontologies!
- [x] For the selection of appropriate annotation properties, I looked at [OMO](https://ontobee.org/ontology/catalog/OMO?iri=http://www.w3.org/2002/07/owl%23AnnotationProperty) first. I understand that aligning ontology metadata and term-level metadata is essential for cross-integration of OBO ontologies.
- [x] If I was not sure about the meaning of any of the checkboxes above, I have consulted with a member of the OBO Foundry for advice, e.g., through the [obo-discuss](https://groups.google.com/g/obo-discuss) Google Group.
- [x] The requested ID space does not conflict with another ID space found in other registries such as the Bioregistry and BioPortal, see [here](https://obofoundry.org/id-policy) for a complete list.

**Comment by pfabry** [comment]
Dear @samie3000, 

Thank you for your submission. The review will be executed as a two stage process. 

- First, you will have to pass the new ontology precheck, including the [OBO NOR Dashboard](https://obofoundry.org/obo-nor.github.io/dashboard/index.html). Pass means that no check _apart from `Users` may be red_.
- After you have successfully passed these verfications, you will be assigned an OBO Operations committee member to review the ontology.

Usually, the review will result in an opportunity for you to improve the ontology. When the reviewer believes the ontology is ready for presentation to the OBO Operations Committee, they will present your ontology during an OBO Operations Call. This gives other members of the committee the opportunity to assess your work.

When a decision is reached by the committee you will be informed here on the issue tracker. The process can take any number of weeks or months, depending on the case at hand. Please inform us about any reasons you might have for increased urgency. You will be informed once your ontology is loaded in the OBO NOR Dashboard.

Good luck!

**Comment by pfabry** [comment]
Dear @samie3000,

Before going any further, the pre-registration checklist needs to be completed in full. In particular, some important OBO foundry [principles](http://obofoundry.org/principles/fp-000-summary.html) need to be followed, such as:

- Ontology IRI and version IRI following OBO Foundry syntax
- Classes and properties IRIs following OBO Foundry syntax
- Definitions using the [IAO:0000115](https://ontobee.org/ontology/IAO?iri=http://purl.obolibrary.org/obo/IAO_0000115) property
- Checking if classes and properties are not already exisitng in OBO Foundry ontologies

Thank you

**Comment by cthoyt** [comment]
Several of the fields in this issue weren't filled out correctly (e.g., contribution guidelines link, ontology downloads link)

Based on the request, this ontology appears to explicitly overlap with existing OBO Foundry ontologies (HP/SYMP for symptoms, DOID/MONDO for diseases). Have you reached out to these ontologies to see if parts of yours would be able to be contributed there?

**Comment by nlharris** [comment]
@samie3000 I hope you saw the questions and suggestions above and will respond soon!

**Comment by msabanluc** [comment]
Hello, my apologies for the late response. I'm managing the Carolio GitHub repository for samie3000. I believe the updated page and version of the ontology meets the requirements on the checklist and should be ready for review. Please let me know if there is anything further we need to do to move forward. We look forward to working with you throughout this process!

**Comment by matentzn** [comment]
> I believe the updated page and version of the ontology meets the requirements on the checklist and should be ready for review.

In response to @msabanluc comment I have _checked all checkboxes above_ which makes this ontology request move to the next stage (reviewer assignment @pfabry), unless any NOR pre-checking requests still fail.

It is important that whoever reviews the ontology takes all comments, including the observations made by @pfabry and @cthoyt  carefully into account during review.

**Comment by pfabry** [comment]
@msabanluc 
Thank you for the update. The ontology will now be added to the NOR dashboard to check any remaining issues.

**Comment by pfabry** [comment]
@msabanluc @samie3000 
The ontology is added to the [NOR dashboard](https://obofoundry.org/obo-nor.github.io/dashboard/index.html).
For the "Open" principle, you should replace `<dc:license>http://creativecommons.org/licenses/by/4.0/</dc:license>` with `<terms:license>http://creativecommons.org/licenses/by/4.0/</terms:license>` in the ontology header.

**Comment by cthoyt** [comment]
It appears that PURLs are encoded incorrectly. Can we please add this as a check to the NOR dashboard? most contributors get the same feedback

```

    <!-- http://purl.obolibrary.org/obo/carolio.owl#radiation_therapy -->

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/carolio.owl#radiation_therapy">
        <rdfs:subClassOf rdf:resource="http:/`/purl.obolibrary.org/obo/OGMS_0000090"/>
        <obo:IAO_0000115>is a treatment that uses high doses of radiation to kill cancer cells and shrink tumors. At low doses, radiation is used in x-rays to see inside body, as with x-rays of your teeth or broken bones. At high doses, radiation therapy kills cancer cells or slows their growth by damaging their DNA.</obo:IAO_0000115>
        <obo:IAO_0000119>https://www.cancer.gov/about-cancer/treatment/types/radiation-therapy</obo:IAO_0000119>
        <oboInOwl:hasOBONamespace>carolio</oboInOwl:hasOBONamespace>
        <oboInOwl:hasRelatedSynonym>radiotherapy</oboInOwl:hasRelatedSynonym>
        <rdfs:label>radiation therapy</rdfs:label>
    </owl:Class>
```

`http://purl.obolibrary.org/obo/carolio.owl#radiation_therapy` should be something like
`http://purl.obolibrary.org/obo/CAROLIO_XXXXXXX`, see https://obofoundry.org/id-policy

**Comment by pfabry** [comment]
> It appears that PURLs are encoded incorrectly. Can we please add this as a check to the NOR dashboard? most contributors get the same feedback
> 
> ```
> 
>     
> 
>     <owl:Class rdf:about="http://purl.obolibrary.org/obo/carolio.owl#radiation_therapy">
>         <rdfs:subClassOf rdf:resource="http:/`/purl.obolibrary.org/obo/OGMS_0000090"/>
>         <obo:IAO_0000115>is a treatment that uses high doses of radiation to kill cancer cells and shrink tumors. At low doses, radiation is used in x-rays to see inside body, as with x-rays of your teeth or broken bones. At high doses, radiation therapy kills cancer cells or slows their growth by damaging their DNA.</obo:IAO_0000115>
>         <obo:IAO_0000119>https://www.cancer.gov/about-cancer/treatment/types/radiation-therapy</obo:IAO_0000119>
>         <oboInOwl:hasOBONamespace>carolio</oboInOwl:hasOBONamespace>
>         <oboInOwl:hasRelatedSynonym>radiotherapy</oboInOwl:hasRelatedSynonym>
>         <rdfs:label>radiation therapy</rdfs:label>
>     </owl:Class>
> ```
> 
> `http://purl.obolibrary.org/obo/carolio.owl#radiation_therapy` should be something like `http://purl.obolibrary.org/obo/CAROLIO_XXXXXXX`, see https://obofoundry.org/id-policy

That's a good point and I was actually writing a issue about this. I believe that the [ID policy]() should specify that a `LOCALID` must be of the form `[0-9]7`, and this information should be available directly in [Principle#3](http://obofoundry.org/principles/fp-003-uris.html).
However, some ontologies registered in the OBO Foundry, the [Human Disease Ontology](http://obofoundry.org/ontology/doid.html) for example, uses URI of the form:  `http://purl.obolibrary.org/obo/IDSPACE#description_of_the_element`, and a lot of annotation properties as well. On one hand we require the use of `http://purl.obolibrary.org/obo/IAO_0000115` for definitions and on the other we use `http://www.w3.org/2000/01/rdf-schema#label` for the label.

**Comment by pfabry** [comment]
@msabanluc @samie3000 
On a technical point of view, the remaining issue with your ontology is the use of URIs for classes that do not follow the OBO Foundry [ID policy](https://obofoundry.org/id-policy) as stated above. Could you please address this issue?

**Comment by msabanluc** [comment]
@pfabry 
To respond to your comment from yesterday, @samie3000 is still the main contact for this ontology, but I can serve as a secondary contact if needed.

We will go ahead and address the the issues regarding the "open" principle as well as the incorrectly encoded URIs.

Aside from the `LOCALID` being a unique (relative to the ontology), 7-digit, zero-padded ID, are there any additional guidelines/conventions that should be followed when creating these?

Thank you for the feedback!

**Comment by pfabry** [comment]
> Aside from the `LOCALID` being a unique (relative to the ontology), 7-digit, zero-padded ID, are there any additional guidelines/conventions that should be followed when creating these?

That's the main issue but you will find the guideline relative to forming identifiers [here](http://obofoundry.org/id-policy).

**Comment by msabanluc** [comment]
@pfabry 
I believe the updated ontology now addresses each of the above comments. Please let me know if any further changes need to be made. Thanks!

**Comment by cthoyt** [comment]
1. License on GitHub repository says CC BY-SA 4.0 and ontology says CC BY 4.0. OBO Foundry only allows ontologies with CC BY 4.0 or CC0. Please update the license
2. Version IRI not annotated inside the ontology
3. Version doesn't follow semantic versioning https://github.com/TootooniLab/CaroliO/blob/850d8c96d3ab408670485aa7fe4271f5e358e293/CaroliO.owl#L34 - Why not just make this simple as 2.0?
4. `http://purl.obolibrary.org/obo/carolio.owl#Definition` appears. there's an IAO term for this
5. Check for typos such as in https://github.com/TootooniLab/CaroliO/blob/850d8c96d3ab408670485aa7fe4271f5e358e293/CaroliO.owl#L167
6. Underscores in labels (e.g., https://github.com/TootooniLab/CaroliO/blob/850d8c96d3ab408670485aa7fe4271f5e358e293/CaroliO.owl#L194C21-L194C34) and camel case in labels (e.g., https://github.com/TootooniLab/CaroliO/blob/850d8c96d3ab408670485aa7fe4271f5e358e293/CaroliO.owl#L352) are not enjoyable to read. please write them with normal spaces
7. Please use ORCID identifiers for contributor information (e.g., change https://github.com/TootooniLab/CaroliO/blob/850d8c96d3ab408670485aa7fe4271f5e358e293/CaroliO.owl#L17 to be `https://orcid.org/<INSERT CORRECT ORCID ID>`)
8. Many terms are still duplicating existing OBO terms. You can use the OLS to search for each term, such as "radiation therapy" to identify that MAXO already covers a lot of the "treatment" branch (see https://www.ebi.ac.uk/ols4/ontologies/maxo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMAXO_0000014)
9. I don't think the purpose of SYMP is to be an "upper level ontology". Why not just contribute things like CAROLIO:0002000 (variceal bleeding) to SYMP or HPO directly?
10. Similarly, why create a new term CAROLIO:0001000 (caroli syndrome) instead of contributing it to either DOID or MONDO?
11. From looking at the new properties defined in this ontology, it appears they are used for axiom injection on DOID or other external temrs. Please see the discussion at https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1443 on whether/when this is okay.


I think there are other things to address but these are thebig ones for now

**Comment by pfabry** [comment]
> @pfabry I believe the updated ontology now addresses each of the above comments. Please let me know if any further changes need to be made. Thanks!

@msabanluc  Thank you for the update. Your ontology will now be reviewed by @handemcginty.

**Comment by msabanluc** [comment]
@cthoyt 
Thank you for the feedback! We've started addressing some of these issues you've pointed out, but I'm wondering if you can answer a few questions I have related to these:

> 2. Version IRI not annotated inside the ontology

We've included the version IRI here: (https://github.com/TootooniLab/CaroliO/blob/050a97b7d714a733d03a7dbdeba55caef7e7b3cb/CaroliO.owl#L16)
Is there a different way to annotate this?

> 3. Version doesn't follow semantic versioning https://github.com/TootooniLab/CaroliO/blob/850d8c96d3ab408670485aa7fe4271f5e358e293/CaroliO.owl#L34 - Why not just make this simple as 2.0?

For each version release, we have a basic (B) and applied (A) version, where the applied version includes more complex axioms to better reflect real world decision making in actual treatment, where the basic version follows the Open World Assumption and is suitable for ontologists and research. Do you have any suggestions for following semantic versioning while maintaining the applied vs basic releases?

> 9. I don't think the purpose of SYMP is to be an "upper level ontology". Why not just contribute things like CAROLIO:0002000 (variceal bleeding) to SYMP or HPO directly?
> 10. Similarly, why create a new term CAROLIO:0001000 (caroli syndrome) instead of contributing it to either DOID or MONDO?

We currently include these in the ontology as a placeholder. The goal is to contribute these to the respective existing ontologies as you mentioned and remove these.

**Comment by nlharris** [comment]
@handemcginty have you had a chance to take a look at this yet?

**Comment by msabanluc** [comment]
@handemcginty Hi, I hope you are well! Do you have any updates on this?

**Comment by lschriml** [comment]
Caroli syndrome has been added to the DO, DOID:0081394. 
It will be publicly available in our next release.
Cheers,
Lynn

**Comment by handemcginty** [comment]
@msabanluc thanks for your patience during the review process and @cthoyt for your feedback.
Based on the [guidelines](https://obofoundry.org/docs/SOP.html#ROOM) and the latest files in the GitHub repo you linked here, I still have some questions and requests for you.
I see that you still haven't updated the issues @cthoyt already listed, for example using underscores in labels. 
I also see several terms that may be added to existing ontologies such as @lschriml 's example of "Caroli syndrome"  and I understand you created them as placeholders. 
So could you please provide us with timelines for your term requests for your placeholder terms? Per the review guidelines, you alternatively can comment on why you needed your own term and how it may be different from the existing terminology.

Another issue regarding the reuse of terms exists when you inject different inverse properties for existing properties, this is the case for your "[treats](https://ontobee.org/ontology/SCDO?iri=http://purl.obolibrary.org/obo/SCDO_1000018)" property.
Could you please provide us with timelines for addressing this issue as well? This has also been addressed previously for this review by @cthoyt, reminding you [here one more time](https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1443). 
Thanks again for your patience and looking forward to viewing the updated version. I will check back in a week and then again in two weeks.

**Comment by msabanluc** [comment]
@handemcginty Thank you for your feedback!

We've uploaded the updated file that address most of the issues listed by @cthoyt. They also address the issue regarding inverse property injection. These changes are not yet reflected in the 'applied' version, but will be shortly.

Regarding placeholder terms, I'm aware of 'caroli syndrome' and 'variceal bleeding'. We are currently identifying any other terms that may fit in existing ontologies and hope to get back to you sometime next week.

**Comment by msabanluc** [comment]
@handemcginty 
After further inspection, I don't believe any of our other terms under treatment need to be added to existing ontologies. Please let me know if there are any specific terms that make more sense in existing ontologies. Regarding duplicates, I see some MAXO terms are also duplicated in other existing ontologies. What are the guidelines regarding duplicate terms with different definitions? I look forward to your review!

**Comment by lschriml** [comment]
@handemcginty -- Hello Hande, can you please touch base on this ticket and provide feedback?

Cheers,
Lynn

**Comment by cthoyt** [comment]
I wrote [a script](https://gist.github.com/cthoyt/d26df3ec12f6a15f3157546c6ebee3a2) that checks for lexical matches between this proposal and existing ontologies in the OBO Foundry. Note that [OBO Principle 10 "Commitment To Collaboration"](https://obofoundry.org/principles/fp-010-collaboration.html) states:

> It is expected that Foundry ontologies will collaborate with other Foundry ontologies, particularly in ensuring orthogonality of distinct ontologies, in re-using content from other ontologies in cross-product definitions where appropriate, and in establishing and evolving Foundry principles to advance the Foundry suite of ontologies to better serve the joint users.


Below are the results. A case can be made that it's okay to duplicate NCIT terms since this is just an obo export of a resource that does not actually participate in the open community.

## Lexical matching returned results

- `CAROLIO:0000411` mild pain
  - [`ncit:C136549`](https://bioregistry.io/ncit:C136549) Neck Pain Score 2 (0.54)
- `CAROLIO:0000412` moderate pain
  - [`ncit:C121394`](https://bioregistry.io/ncit:C121394) Moderate Extremity Pain (0.54)
  - [`ncit:C136551`](https://bioregistry.io/ncit:C136551) Neck Pain Score 4 (0.54)
- `CAROLIO:0000413` no pain
  - [`ncit:C119987`](https://bioregistry.io/ncit:C119987) Had No Pain (0.54)
  - [`ncit:C121390`](https://bioregistry.io/ncit:C121390) No Extremity Pain (0.54)
  - [`ncit:C136547`](https://bioregistry.io/ncit:C136547) Neck Pain Score 0 (0.54)
- `CAROLIO:0000414` severe pain
  - [`ncit:C121395`](https://bioregistry.io/ncit:C121395) Severe Extremity Pain (0.54)
  - [`ncit:C136553`](https://bioregistry.io/ncit:C136553) Neck Pain Score 6 (0.54)
- `CAROLIO:0001000` caroli syndrome
  - [`doid:0081394`](https://bioregistry.io/doid:0081394) Caroli syndrome (0.772)
  - [`mondo:0018808`](https://bioregistry.io/mondo:0018808) Caroli syndrome (0.772)
- `CAROLIO:0003100` endoscopic treatment
  - [`ncit:C16546`](https://bioregistry.io/ncit:C16546) Endoscopic Procedure (0.54)
- `CAROLIO:0003120` endoscopic retrograde cholangiopancreatography
  - [`maxo:0035049`](https://bioregistry.io/maxo:0035049) endoscopic retrograde cholangiopancreatography (0.778)
  - [`ncit:C16430`](https://bioregistry.io/ncit:C16430) Endoscopic Retrograde Cholangiopancreatography (0.762)
- `CAROLIO:0003200` interventional radiology procedure
  - [`ncit:C63334`](https://bioregistry.io/ncit:C63334) Interventional Radiology Procedure (0.762)
- `CAROLIO:0003210` locoregional therapy
  - [`ncit:C25388`](https://bioregistry.io/ncit:C25388) Local-Regional (0.54)
  - [`ncit:C94796`](https://bioregistry.io/ncit:C94796) Locally Recurrent Malignant Neoplasm (0.54)
- `CAROLIO:0003220` paracentesis
  - [`maxo:0035106`](https://bioregistry.io/maxo:0035106) paracentesis (0.778)
  - [`ncit:C15310`](https://bioregistry.io/ncit:C15310) Paracentesis (0.762)
- `CAROLIO:0003250` transjugular intrahepatic portosystemic shunt
  - [`ncit:C126288`](https://bioregistry.io/ncit:C126288) Transjugular Intrahepatic Portosystemic Shunt (0.762)
- `CAROLIO:0003300` pharmaceutical treatment
  - [`maxo:0000058`](https://bioregistry.io/maxo:0000058) pharmacotherapy (0.556)
- `CAROLIO:0003310` antibiotic treatment
  - [`ncit:C258`](https://bioregistry.io/ncit:C258) Antibiotic (0.762)
  - [`chebi:33281`](https://bioregistry.io/chebi:33281) antimicrobial agent (0.556)
  - [`xco:0000482`](https://bioregistry.io/xco:0000482) antimicrobial agent (0.556)
- `CAROLIO:0003320` antiemetic treatment
  - [`chebi:50919`](https://bioregistry.io/chebi:50919) antiemetic (0.778)
  - [`xco:0001245`](https://bioregistry.io/xco:0001245) antiemetic (0.778)
  - [`ncit:C267`](https://bioregistry.io/ncit:C267) Antiemetic Agent (0.556)
- `CAROLIO:0003330` bile acid treatment
  - [`chebi:3098`](https://bioregistry.io/chebi:3098) bile acid (0.778)
  - [`chebi:22868`](https://bioregistry.io/chebi:22868) bile salt (0.549)
  - [`ncit:C74800`](https://bioregistry.io/ncit:C74800) Bile Acid Measurement (0.54)
- `CAROLIO:0003340` chemotherapy
  - [`maxo:0000647`](https://bioregistry.io/maxo:0000647) chemotherapy (0.778)
  - [`ncit:C15632`](https://bioregistry.io/ncit:C15632) Chemotherapy (0.762)
- `CAROLIO:0003350` diuretics treatment
  - [`chebi:35498`](https://bioregistry.io/chebi:35498) diuretic (0.778)
  - [`xco:0000122`](https://bioregistry.io/xco:0000122) diuretic (0.778)
  - [`ncit:C448`](https://bioregistry.io/ncit:C448) Diuretic (0.762)
- `CAROLIO:0003360` octreotide treatment
  - [`chebi:7726`](https://bioregistry.io/chebi:7726) octreotide (0.778)
  - [`ncit:C711`](https://bioregistry.io/ncit:C711) Octreotide (0.762)
- `CAROLIO:0003370` proton pump inhibitor treatment
  - [`xco:0000577`](https://bioregistry.io/xco:0000577) proton pump inhibitor (0.778)
  - [`ncit:C29723`](https://bioregistry.io/ncit:C29723) Proton Pump Inhibitor (0.762)
  - [`chebi:49200`](https://bioregistry.io/chebi:49200) EC 3.6.3.10 (H(+)/K(+)-exchanging ATPase) inhibitor (0.556)
- `CAROLIO:0003380` pruritus treatment
  - [`hp:0000989`](https://bioregistry.io/hp:0000989) Pruritus (0.762)
  - [`ncit:C3344`](https://bioregistry.io/ncit:C3344) Pruritus (0.762)
  - [`scdo:0000935`](https://bioregistry.io/scdo:0000935) Pruritus (0.762)
  - [`symp:0000432`](https://bioregistry.io/symp:0000432) itching (0.556)
  - [`ncit:C58006`](https://bioregistry.io/ncit:C58006) Pruritus, CTCAE (0.54)
- `CAROLIO:0003400` radiation therapy
  - [`maxo:0000014`](https://bioregistry.io/maxo:0000014) radiation therapy (0.778)
  - [`ncit:C15313`](https://bioregistry.io/ncit:C15313) Radiation Therapy (0.762)
- `CAROLIO:0003500` surgical treatment
  - [`ncit:C15329`](https://bioregistry.io/ncit:C15329) Surgical Procedure (0.54)
- `CAROLIO:0003510` organ transplant
  - [`ncit:C122934`](https://bioregistry.io/ncit:C122934) Organ Graft (0.54)
- `CAROLIO:0003520` roux-en-y
  - [`ncit:C51756`](https://bioregistry.io/ncit:C51756) Roux-en-Y Anastomosis (0.549)
- `CAROLIO:0003530` surgical resection
  - [`maxo:0000448`](https://bioregistry.io/maxo:0000448) surgical resection (0.778)
  - [`ncit:C158758`](https://bioregistry.io/ncit:C158758) Resection (0.54)

## Lexical matching returned no results

- `CAROLIO:0000400` value partition
- `CAROLIO:0000410` pain scale
- `CAROLIO:0000420` symptom recurrence status
- `CAROLIO:0000421` non-recurrent symptom status
- `CAROLIO:0000422` recurrent symptom status
- `CAROLIO:0002000` variceal bleeding
- `CAROLIO:0003110` endoscopic band ligation
- `CAROLIO:0003121` biliary drainage
- `CAROLIO:0003122` biliary dilatation
- `CAROLIO:0003123` biliary stent placement
- `CAROLIO:0003124` gallstones removal
- `CAROLIO:0003230` percutaneous aspiration and drainage
- `CAROLIO:0003240` percutaneous transhepatic cholangiogram

However, these have big overlap with MAXO and SYMP/HP, and should be considered to be submitted there.

**Comment by handemcginty** [comment]
Thanks again @cthoyt for all your help during this review including the script you wrote to check the overlapping list of terms. @msabanluc I assume that you are still reviewing these terms and identifying overlapping terms. In the previous meeting, the operations committee agreed that we would ask you to create git issues for overlapping terms. We understand that there may be a delay in the creation of these terms in the target ontologies, however, lack of effort is against the OBO guidelines for accepting the ontology as is.
Thanks again for your patience and please let us know when there is an updated version.

**Comment by msabanluc** [comment]
Hi @handemcginty, thank you for the update. We've started reviewing these terms and will address terms overlapping with MAXO such as:

- endoscopic retrograde cholangiopancreatography
- paracentesis
- pharmaceutical treatment/pharmacotherapy
- chemotherapy
- radiation therapy
- surgical resection

Can you please clarify what you mean by creating git issues for these?


We believe the other CAROLIO terms listed are unique and do not overlap with the suggested terms.
We've also begun reflecting changes in the ontology, which will be available on our GitHub page soon.
For example, we've added the DOID definition of 'Caroli syndrome' (DOID:0081394). 

We've also contributed our definitions to ontology terms without existing definitions, such as: 
[SYMP_0000421](http://purl.obolibrary.org/obo/SYMP_0000421) - Hematochezia 
and 
[SYMP_0000295](http://purl.obolibrary.org/obo/SYMP_0000295) - Hepatic abscess

I will let you know when the updated version reflecting these changes is available. Thanks!

**Comment by handemcginty** [comment]
Thank you so much for the update @msabanluc . What I meant by creating git issues is that we wanted to see git issues for requests for new term additions or edits to existing terms for the terms outlined previously. Thanks again and looking forward to your ping when you are ready.

**Comment by nlharris** [comment]
@msabanluc just wondering how this is going!

**Comment by handemcginty** [comment]
@msabanluc Due to inactivity for the past two months, this issue will be closed. When you are ready, you are welcome to open this issue again. Thanks for your interest in submitting your ontology to OBO Foundry.
