### ISSUE TITLE
Should OBO context JSON-LD file contain a prefix `obo`?

### ISSUE THREAD

**Issue by cthoyt** [OBOFoundry/OBOFoundry.github.io#2462]
The OBO context JSON-LD file at http://purl.obolibrary.org/meta/obo_context.jsonld contains preferred prefixes for OBO Foundry ontologies with their corresponding URI prefixes. However, it does not contain the prefix `obo` (which would correspond to the top-level namespace http://purl.obolibrary.org/obo/).

This might be helpful for people using the `curies` package to compress other things living in the OBO namespace, such as GO_REF, UBPROP, and others.

**Comment by matentzn** [comment]
@cthoyt can you give us an indication of how important this is to you? I am worried that about:

<img width="493" alt="image" src="https://github.com/OBOFoundry/OBOFoundry.github.io/assets/7070631/0c61b71d-56a6-4f2f-b25d-63d36591b88c">

(because of the problem that maybe not everyone knows they need to prefer the longest match)

I don't see yet a clear advantage for adding this here rather than just having this in bioregistry? The examples you give are all unsupported URL spaces.. (I am not trying to argue that the prefix isn't useful, just that it has to be added here)

**Comment by cthoyt** [comment]
This is pretty low priority. I was just thinking about it based on a question from the `curies` package https://github.com/cthoyt/curies/issues/63 where some things get compressed to `obo:UBPROP_000006` but I realized when writing up the examples into unit tests that this wasn't actually possible if I start with the OBO Foundry converter.

I like your xkcd. It's another reminder that we should all be using standard code for handling prefix maps. We have a java and python implementation, I guess early 2024 I will be scheduled to write this in Javascript, R, and Rust if all goes well.
