### ISSUE TITLE
OBO Foundry domain names expire in one month

### ISSUE THREAD

**Issue by lschriml** [OBOFoundry/OBOFoundry.github.io#252]
@alanruttenberg @cmungall 

I was just looking at our obofoiundry.operations gmail account, our domains: obofoundry.net and obofoiundry.com will expire in one month. Who has the codes for these domains, to allow us to pay for their registration ?

**Comment by cmungall** [comment]
cc @kltm

**Comment by alanruttenberg** [comment]
Lynn, you, for one, have the codes. Recall that I created a gmail account and told a few people (anyone who wanted) what the password was. The hope was that there would be a number of people who could send money to the account in order to renew the domains. 

I just renewed obofoundry.com with funds already there (donated by me and Lynn). There are insufficient funds to renew the .net address. I guess I will send enough money to cover it for another year. Folks who want to contribute can use google wallet to send the account, or me, some funds.

**Comment by alanruttenberg** [comment]
We should have obofoundry.org transferred into that account as well. Then get people to contrib enough for 5 years renewal ($180) and have email from the account forwarded to the twg, operations committee, etc.

**Comment by alanruttenberg** [comment]
I have renewed obofoundry.net as well now. I couldn't send money using google wallet fast enough (looks like it takes 2 business days) so I added, payed with, and removed one of my credit cards.

**Comment by nlharris** [comment]
I'm pretty sure this can be closed, right?
