### ISSUE TITLE
id-policy doc has a link to sharedname.org which has been domain squatted

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#2565]
https://obofoundry.org/id-policy

@alanruttenberg do you have any alternative links?

Shall we also mention bioregistry here cc @cthoyt

**Comment by cmungall** [comment]
We can also provide some practical recommendations linking here https://oboacademy.github.io/obook/howto/idrange/

**Comment by alanruttenberg** [comment]
The only thing would be the wayback version: https://web.archive.org/web/20170526125335/http://sharedname.org/page/Main_Page

But it's probably time to update with a source that's more current

**Comment by nlharris** [comment]
@alanruttenberg any suggestions?

**Comment by alanruttenberg** [comment]
I don't

**Comment by matentzn** [comment]
Its really interesting that something that provided the foundation to some of our best practices basically just disappeared of the web:

```
https://www.google.com/search?q=%22Shared+Name+Initiative%22
```

@nlharris this is not that important an issue, just replace the hyperlink with the web archive link @alanruttenberg provided and make a note that the original resource has since disappeared.
