### ISSUE TITLE
How to refer to OFOC members who are not actively contributing to operations (meetings, working groups)?

### ISSUE THREAD

**Issue by nicolevasilevsky** [OBOFoundry/OBOFoundry.github.io#2576]
This discussion was started on the OFOC on 2024-04-16.

The open question is - how do we refer to former OFOC members who are still contributing to the OBO Foundry but not actively participating on the OFOC

Potential terms:

- alumni (_note, there has been opposition to this term_)
- emeritus
- contributor
- founding member

**Comment by matentzn** [comment]
The main issue here is political. There are a few "lifetime members" like @alanruttenberg who dont join meetings or participate in working groups, but should still be considered part of operations due to the wider role they played and still play.

My suggestion is to split the list of _current_ OFOC (OBO Foundry Operations Committee) members into three groups for now:

1. Active committee members. These will be allocated the regular duties like ontology review, meeting chairing etc.
2. Founding members. These will not be allocated regular duties, but they will still be technically considered "active". This list is very different from "Alumni", who are not considered active anymore.
3. Strategic advisors. These are people like @cmungall  and @mellybelly  that invest a lot of people-power and know-how into OBO, but are outside of duty rotation / dont often take part in meetings. I guess this could be something like a "steering" committee that sits on top of OFOC, but no need to get lost in that rabbit hole right now.

Once we have done this split (in our duty rotation spreadsheet), we see who is not covered by this list and discuss what to do.

Remember, the whole point of this exercise is to relieve pressure on active WG members by exempting them from ontology reviewing and meeting preparation duties, and generally increase involvement from all OFOC members (#2561), rather than having the same 5 people volunteering to do most jobs.

Of course, some intervention like this also fosters a culture of "exclusion" rather than "inclusion", so we have to be a bit mindful of the question whether the social cost of moving people to "Alumni" status as a consequence of this thing here will be really worth it.

**Comment by nicolevasilevsky** [comment]
based on the conversation on the OFOC call on 2024-04-30, I am drafting an email to the OBO mailing list with the subject: Clarification of Role and Contribution Tracking for OBO Foundry Operations Committee (OFOC) Members

This is still on my to do list and I hope to get to it soon. I'm working on the draft with @matentzn and @nlharris

**Comment by nicolevasilevsky** [comment]
The form is closed and the responses are [here](https://docs.google.com/forms/d/10pzwJq4jv1Wln-_Uj_mNumDiJ6KMHxCLcqimKkU4Zaw/edit#responses). The next steps need to be determined.

**Comment by nicolevasilevsky** [comment]
Discussed on the OBOF call on 2024-09-03

- We will resend the email to the OBO Mailing list and try to explicitly explain that inactive members will be moved into an 'alumni' (or other label) status
- Nicole will draft an email, to be reviewed by the OFOC by Friday, Sept 06
- Nicole will send the email to the OBO mailing list on Monday, Sept 09
- We will ask for responses from the OBO discuss recipients by Friday, Sept 27
- On/after Sept 30, we will convert inactive members (who did not reply to the form) to inactive/alumni

**Comment by nicolevasilevsky** [comment]
Update- as of 2024-09-17, I have send the email to the mailing list and will wait for responses until after Sept 27. We have 17 responses to the form so far. On/after Sept 30, we will convert inactive members to inactive/alumni status.

**Comment by nicolevasilevsky** [comment]
Note, we still need to update the membership page: https://github.com/OBOFoundry/OBOFoundry.github.io/issues/2496
