### ISSUE TITLE
Requesting a non-ontology PURL, for SHACL validation checks

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#276]
@balhoff has some SHACL validation checks that are widely applicable across multiple ontologies. The SHACL is expressed as RDF, but it not really an 'ontology' in the OBO sense. However, it would be useful to have a purl for these, so that people can point to this in their pipelines and not worry about underlying repo changing etc. We were thinking `/obo/validations/`

**Comment by jamesaoverton** [comment]
Having PURLs for tools is a good idea. Naming is hard. If this is SHACL-specific, then I'm not sure that "validations" is the best name, since I can imagine other projects using different tools for validation. We might want more of these tool PURLs, but I don't think they should complete with ontologies for names. Maybe `/obo/tools/*` or something?

**Comment by balhoff** [comment]
@jamesaoverton I like "tools", good idea. The file could be something like `/obo/tools/qc-shapes.ttl`.

**Comment by alanruttenberg** [comment]
I'd put it parallel to /obo/ rather than below it
a) there's no particular positive to having it below /obo/
b) there's potential negative in having to check that it doesn't conflict
with anything we said in id-policy and potential confusion with ontologies

If there's an ontology to go along with the tools, explaining what they do,
for instance, that might be a candidate for being below /obo/

A

**Comment by balhoff** [comment]
I would like to create `http://purl.obolibrary.org/tools/qc-shapes/`. Will it work if I submit a pull request with a `tools-qc-shapes.yml` in [config](https://github.com/OBOFoundry/purl.obolibrary.org/tree/master/config), with base_url `/tools/qc-shapes`? Or does something extra need to happen to create the parallel directory?

**Comment by jamesaoverton** [comment]
Using `tools/` breaks some assumptions that I built into the PURL system. We'll have to take a closer look at the code. I can't do that this week, but you're welcome to give it a shot.

**Comment by jamesaoverton** [comment]
I haven't had time to do this properly, and now it's looking like I won't have time until the middle of August. So here's my suggestion: Please open a new issue with all the details of what PURLs should redirect where, and we'll hack a quick solution.

https://github.com/OBOFoundry/purl.obolibrary.org/issues

**Comment by cmungall** [comment]
Good points. "tools" could become a bit limiting, not sure I have good 
alternatives. Choices are:

  * tools
  * architecture
  * infrastructure
  * internal
  * docs (including RDF, OWL 'documents')
  * meta

**Comment by nlharris** [comment]
what is the status of this?

**Comment by cmungall** [comment]
We now have `/meta/` thanks to @jamesaoverton 

e.g. http://purl.obolibrary.org/meta/obo_prefixes.ttl

(we should put these as PURLs on the main site)

This is pretty easy to set up:

https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/www/.htaccess

I suggest we follow James' advice from 4 years ago and open individual tickets/PRs on PURL repo as needed, so closing this for now
