### ISSUE TITLE
Add list of listserves to OBO site

### ISSUE THREAD

**Issue by mellybelly** [OBOFoundry/OBOFoundry.github.io#295]
We used to maintain a list of lists, these seem to only be available from within a project's homepage now. Some have gone quite quiescent, others moved. Time to do an inventory? Could also link relevant lists to individual ontologies, e.g. anatomy list to ZFA, Uberon, etc. While I do think having a person's contact is important, having a separate listserve contact would also be nice as sometimes it is more relevant to have the email go to a listserve.

**Comment by cmungall** [comment]
legacy file:
http://obo.cvs.sourceforge.net/viewvc/obo/obo/website/cgi-bin/mailing-lists.txt

Many of these have been moved into the mailing_list field of the ontology's .md file (the full set can be queried from the combined yml/json/rdf that gets built). This is not very visible yet in the html.

This doesn't really topic-centric lists that do not belong to one ontology or another, it might be an idea to reinstate the old file as yml.

Then again, so many of the lists are quiescent, it might be better to have a freeform page with a list of some of the most active topic-centric lists.

**Comment by cmungall** [comment]
We decided we don't need to have a master page with all mailing lists harvested from the metadata from each ontology.

However, each ontology page should show the link to the mailing list if this is present in the metadata (currently not shown). This could also be shown on the front page.

**Comment by nlharris** [comment]
Is this done, or is it something that still needs to be done? If the latter, is @cmungall the only person who can address this?

**Comment by nlharris** [comment]
i'm unassigning chris.

also, IMHO any ticket that mentions "listserves" is probably so out of date that it could be closed as obsolete.

**Comment by nlharris** [comment]
> each ontology page should show the link to the mailing list if this is present in the metadata (currently not shown).
Should we make a separate ticket for that, or change the title of this ticket?

> This could also be shown on the front page.
You mean, add a mailing list icon in the obofoundry.org ontology table (in addition to the envelope that mails the ontology developers)?

**Comment by nlharris** [comment]
tagging @nicolevasilevsky who may have thoughts about this.

**Comment by nicolevasilevsky** [comment]
There is a mail icon, looks like it links to a specific person, not a mailing list. We could just change it to the mailing list instead of going to an individual?

(I don't know how to do this in bulk, but could probably do each one manually).

![image](https://user-images.githubusercontent.com/6722114/105926260-87cec280-5ff6-11eb-8db5-f4712e7d8b15.png)

**Comment by jamesaoverton** [comment]
Chris said: "each ontology page should show the link to the mailing list if this is present in the metadata (currently not shown)."

I see links to the mailing lists on the ontology pages. So I think this issue should just be closed.

Chris also said "This could also be shown on the front page" and I guess @nicolevasilevsky's is proposing that. It's more work and I don't see a big benefit.

The registry entries have a required `contact` field with a required `email` subfield. We use that contact as the [Locus of Authority](http://www.obofoundry.org/principles/fp-011-locus-of-authority.html) and so we've been requiring that this is a single person (with decision making authority) and not just a mailing list. There has been plenty of discussion about that over the years.

The mail icon in the table of ontologies uses the `contact.email` field of the registry entry for each ontology. This is driven by some code and a template.

There's also an optional `mailing_list` field that some ontologies have. I guess we could change the main table to use `mailing_list` instead of `contact.email`, but it would take some work and I don't see a big advantage.

**Comment by matentzn** [comment]
I agree this issue should be closed - given the sparsity of mailing lists in the annotations using the contact email is better IMO.

**Comment by nicolevasilevsky** [comment]
+1 to close.
