### ISSUE TITLE
Update SBO ontology

### ISSUE THREAD

**Issue by simonjupp** [OBOFoundry/OBOFoundry.github.io#296]
The purl for SBO redirects to OWL file on the berkleybop server but this file is very out of date. EBISPOT/OLS#107

**Comment by cmungall** [comment]
Is this ontology abandoned? The tracker link is to sourceforge.

The ontology needs to have an ontology IRI declaration. Add this to the obo:

```
ontology: sbo
```

**Comment by cmungall** [comment]
In general it's much better if everyone takes care of their own releases. This can be done easily if an ontology is set up using the [starter kit](https://github.com/cmungall/ontology-starter-kit).

For legacy .obo ontologies, we build owl centrally, this requires maintenance of a build tag see http://obofoundry.org/faq/what-is-the-build-field.html

This is sensitive to errors in the source ontology. These can be annoying to debug as everything is combined into one jenkins job, and we pass the whole job unless what we tag as infallible jobs fail. To see why an individual ontology is failing, pore through http://build.berkeleybop.org/job/simple-build-obo-all/lastBuild/consoleFull

For this particular error case, the output is kind of inscrutable:

```
Thu Jun 16 10:34:37 PDT 2016 ::   RUNNING: mv src/sbo.obo src/sbo.obo.prev
Thu Jun 16 10:34:37 PDT 2016 :: Missing obo or owl files for sbo
```

This is because oort names the files based on ontology id, which was missing here. I fixed the build tag to instruct the pipeline to insert this automatically. Will be fixed next cycle at midnight

**Comment by simonjupp** [comment]
Thanks. I don't see some of the legacy .obo ontologies moving to manage their own OWL builds anytime soon.

**Comment by simonjupp** [comment]
Doesn't look like it picked up the ontology name again  http://build.berkeleybop.org/job/simple-build-obo-all/lastBuild/consoleFull

2016-08-10 22:45:07,838 INFO  (ParserWrapper:76) Finished loading ontology: http://purl.obolibrary.org/obo/TEMP from: file:/srv/nfs/share/jenkins/workspace/simple-build-obo-all/src/sbo.obo
2016-08-10 22:45:07,977 INFO  (OboOntologyReleaseRunner:47) OntologyChecks for TEMP:

**Comment by cmungall** [comment]
Sorry, forgot to run the build step
