### ISSUE TITLE
Decide on policy for ncit PURL

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#348]
We have never had an OBO purl for NCIT, this is a problem. See https://github.com/OBOFoundry/OBOFoundry.github.io/issues/344

Broadly there are a few options

 1. Remove/obsolete NCIT from registry
 2. Place NCIT in a special category of ontologies-of-interest that may have an external ontology URL
 3. Make a working OBO PURL

For the last option - should this be a simple redirect? Or should it resolve to a rewritten ontology that conforms to OBO norms?

cc @mellybelly @NCIEVS

**Comment by mellybelly** [comment]
+1 for making a working OBO PURL and yes we need an NCIT that conforms to OBO standards.

**Comment by jamesaoverton** [comment]
I owe @cmungall some hours on the [ncit-obo](https://github.com/ontodev/ncit-obo) project. I can work on it later in December.

**Comment by alanruttenberg** [comment]
I think we should tread carefully here. Rewriting someone else's currently maintained ontology without their participation, while perhaps allowable according to license, doesn't seem consistent with what we would expect use of OBO ontologies to be.

If the issue is having OBO compatible metadata, then a friendlier way to do this would be to have an auxiliary file which imports the original and copies annotations to new properties. Wouldn't it be possible to generate the additional annotations just using Ontofox?

It is unfortunate that the NCIT urls don't resolve to page-per term as the OBO ontologies do. Since the ontology is of such importance, perhaps we might approach NCI about them having the NCIT become part of the OBO foundry and do a one-time rewrite of their URLs as we did with our legacy PURLS. A tighter integration of NCIT with the rest of the OBO would benefit all parties, I would think.

**Comment by mellybelly** [comment]
We are doing contract work with NCIT team to make this happen, so no concerns about "Rewriting someone else's currently maintained ontology without their participation."

The goal of the contract work is in part to do the mapping of annotations to OBO properties.

**Comment by jamesaoverton** [comment]
Regarding the narrow point about OBO compatible metadata and OntoFox:

In OBO we often have one or two levels of OWL annotation axioms to provide additional information about a given axiom. The NCIt OWL file provides that kind of information using XML literals with one or two levels of hierarchy. So I wrote some code to translate their XML to one or more OWL annotations. Then we ran into some problems with escaping inside XML literals (either in the source file or in OWLAPI processing or in my code, haven't dug deep yet). So it turns out that generating OBO compatible metadata from NCIt is a little tricky.

**Comment by mellybelly** [comment]
part of the contract is actually to inform NCIT future plans, so this is a great opportunity :-)

**Comment by NCIEVS** [comment]
Over here we've talked in the past about using PURLs.  We need to resurrect the topic on this end.  @jamesaoverton, yes, owl1 didn't deal well with annotations, but those xmlliterals will go when we transition to owl2.  we have some owl2 conversions (non-production at this time) that we are testing and in protege the annotations on annotations do the trick very well; I believe @cmungall 's conversion dealt with them as well (?).

**Comment by cmungall** [comment]
> I believe @cmungall 's conversion dealt with them as well 

That's @jamesaoverton's work :-)

**Comment by alanruttenberg** [comment]
@mellybelly cool
@jamesaoverton Ah, forgot about the XML literals. Yes, escaping is bitch. I've dealt with this somewhat in code I have - let me know if you need an extra pair of eyes. (CDATA is your friend)

**Comment by cmungall** [comment]
Can we close this now?

**Comment by balhoff** [comment]
Seems like it.
