### ISSUE TITLE
VersionIRIs

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#364]
_From @alanruttenberg on January 4, 2017 16:58_

I was doing a release for IAO and noting the versionIRIs so that the released versions could use them. However the following ontologies did not have versionIRIs.

Recommendation: Build tools should ensure that versionIRIs are added as appropriate and that unversioned imports are changed to versioned ones for the release files.

"http://purl.obolibrary.org/obo/ro/core.owl"
"http://purl.obolibrary.org/obo/ro/bfo-axioms.owl"
"http://purl.obolibrary.org/obo/ro/annotations.owl"
"http://purl.obolibrary.org/obo/ro/bfo-classes-minimal.owl"

_Copied from original issue: OBOFoundry/Operations-Committee#195_

**Comment by nlharris** [comment]
Was this addressed by the closed PR?

**Comment by matentzn** [comment]
This is generally covered by the OBO dashboard, but we don't require _all_ release artefacts to have version iris.. this ticket in general will never close. Specifically for RO this could be fixed, but needs to be moved to RO repo.

**Comment by alanruttenberg** [comment]
Not sure which PR is being referred to.

If you mean the lack of version IRI can't be fixed, I think it can be, by
having releases of ontologies create their own static versions with a
version IRI the releasing ontology designates. That's what I did at some
point for IAO releases - copy the current version of unversioned ontologies
to the release directory, assign them new versionIRIs and have the main
product import using these new versionIRIs.

From the perspective of someone who chooses to use a specific version of an
ontology, the point of using a version IRI in an import is to ensure
stability of an application that uses the ontology, same reason as
specifying a version of a software dependency. So if the things
transitively imported can change then I think the benefit of using a
versionIRI is lost.

Alan

**Comment by matentzn** [comment]
Yes, sorry, I was not clear. We already have standard processes to automatically release RO and many other ontologies, and attach versionIRIs to them, see for example [here](https://github.com/oborel/obo-relations/blob/master/ro-base.owl#L21) for an example in RO. However, RO in particular has many different release files, like bfo-classes-minimal and others, and I am not sure all of these get version IRIs..

**Comment by alanruttenberg** [comment]
That's the merged ontology, right? There's no problem with those since
there's no owl:importing of ontologies. As far as the annotations go it can
be advertised, if true, that any unversioned ontologies that were merged
were their latest as of the date in the versionIRI. As a minor aesthetic
tweak, you might consider removing the string "VersionIRI(&lt;null&gt;))".

The issue I was concerned with were releases of unmerged ontologies. I
suppose there could be a policy that only merged ontologies get version
IRIs. But if the unmerged ontologies continue to be released as versioned
products then that's where the copy/allocate IRI/import new IRI strategy
would apply, as way of making sure the client gets the same thing every
time they access the versioned IRI.

Alan

**Comment by matentzn** [comment]
Oh yes, we do not ever deal with versionIRIs on imports.. Thats right. We only add them on the merged artefacts. In fact, we discourage now everywhere the publication of unmerged ontologies precisely because they are not as easily versioned (because you would have to add versioned import statements, versioned imports, and more).

**Comment by matentzn** [comment]
we now only release merged products for easier versioning. I don't see this changing!

**Comment by alanruttenberg** [comment]
Close as wont fix is my impression.
