### ISSUE TITLE
Ability to sort ontologies list by column header

### ISSUE THREAD

**Issue by mcourtot** [OBOFoundry/OBOFoundry.github.io#43]
Suggested by Erick Antezana on obo-discuss:
- it would be great to be able to sort the ontologies (e.g. by name, by modification date, by prefix, ...)

Note: see #2 - for now we just listed Foundry at the top.

**Comment by mcourtot** [comment]
adding @easr

**Comment by cmungall** [comment]
Actually, why don't we just do this here for now

https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/util/extract-metadata.py#L58-L71

OK, the 'proper' place is in the display layer, but maybe this could be revisited as a push to have user-sortable tables (and then just do the default sort order here, rather than in liquid). I had a very brief look for some js sortable tables but none seemed ideal.

**Comment by nlharris** [comment]
what's the status of this?

**Comment by matentzn** [comment]
We have recently been back and forth about this issue and I think we need to consider moving to a more dynamic framework for the table.. Simple declarative was nice, but in the long run we want faceted search and sorting, and our tech stack does not cut if for that..

**Comment by nlharris** [comment]
I think this issue is redundant with #1241. Should we close one of them?

**Comment by nlharris** [comment]
Now done! 🙌
