### ISSUE TITLE
Check status: FIX

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#470]
@jannahastings is this ontology still active?

**Comment by jannahastings** [comment]
Hi @cmungall, as far as I know there was no active development on FIX (or REX for that matter) since the last date of update -- I just checked and that was May 2005 (!). We kept them alive as archives within the ChEBI downloads area for the last few years, because there were no ontologies that directly adopted them or took over all the content, and there were users at that time. I'm not sure what the current situation is with respect to usage.

**Comment by rvita** [comment]
This ontology will be maintained at EBI and ChEBI is working on finding it a permanent home, but at this time it is deemed inactive.

**Comment by rvita** [comment]
Janna Hastings @jannahastings states that fix is orphaned

**Comment by nlharris** [comment]
FIX not yet marked obsolete on obofoundry.org

**Comment by jamesaoverton** [comment]
FIX is not obsolete, it is orphaned, which means it has no active contact. This PR made updated its status #786 

We should do a better job of distinguishing orphan status on the main table, but that's being dealt with here #1126.
