### ISSUE TITLE
Domain gaps in OBO Foundry

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/OBOFoundry.github.io#601]
_From @GoogleCodeExporter on August 12, 2015 2:3_

```
As per older meeting discussions, the Editorial WG should create a list of 
domain gaps in the OBO Foundry. Which domains, which are currently not covered 
in an OBO library ontology, would allow for better logical inference or more 
complete data annotation?
```

Original issue reported on code.google.com by `rlwalls2...@gmail.com` on 16 Aug 2013 at 11:27

_Copied from original issue: OBOFoundry/Operations-Committee-RETIRED#100_

**Comment by jamesaoverton** [comment]
_From @GoogleCodeExporter on August 12, 2015 2:3_

Original comment by `mcour...@gmail.com` on 16 Oct 2013 at 7:59

**Comment by nlharris** [comment]
i don't know, this seems borderline out of scope to me and unlikely to ever get done. i would vote to just close it as "won't do".

**Comment by nataled** [comment]
I agree with @nlharris to close. In a sense, the work with COB will allow us to see gaps more clearly. @jamesaoverton do you agree?

**Comment by jamesaoverton** [comment]
My name is on this issue because I run the issue migration tool, but the issue was created by @ramonawalls and/or @mcourtot. However I agree that it's fine to close this very old issue.

**Comment by nataled** [comment]
In that case I'm going to close it. It did indeed come from Ramona, and it was because the EWG many years ago thought this was something we should do. At the time we didn't really have a good way to do it, so it languished. We needed to have that 'domain' metadata tag fleshed out and have all ontologies provide an ACCURATE indication of the domain. As mentioned, once we have COB fully done and annotated with ontologies, the objective indicated in this issue will easily fall from that.
