### ISSUE TITLE
Add usage information on which MODs use which ontologies

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#607]
MODs use a variety of ontologies in their annotations. We should capture this in the usage field

E.g. 
ftp://ftp.flybase.net/releases/current/precomputed_files/ontologies/
ftp://ftp.rgd.mcw.edu/pub/data_release/

**Comment by jonquet** [comment]
Are you looking for a property to represent the information: "the project/database/organization X uses ontology Y" ? If yes, then I can tell we have not found such property in the 23 metadata vocabularies reviewed when we refactor AgroPortal's ontology metadata model. 

To my knowledge BioPortal is the only platform that capture such a relation with their ontology/project relation. 
Within AgBioData initiative, we have reused this feature to capture the results of a survey done to all the DBs of this group and the result is now stored in AgroPortal. For instance all the ontologies used by the Planteome project are available here:  http://data.agroportal.lirmm.fr/projects/Planteome
The other way arround, all the project which use TO are available at: http://data.agroportal.lirmm.fr/ontologies/TO/projects

As you see, the metadata properties used are "http://data.bioontology.org/metadata/Ontology/ontolgyUsed" and "projects" which is not branded by NCBO as a metadata vocabulary.

More recently in our MOD proposition (https://github.com/sifrproject/MOD-Ontology)... work in progress, inside MOD1.2 (http://www.lirmm.fr/~jonquet/publications/documents/Article_MTSR-2017_MOD1.2.pdf)
We have created a property mod:ontologyInUse in the MOD name space because as said we have not found one to use in any of the 23 reviewed vocab.

**Comment by jonquet** [comment]
Well, to summarize, I suggest to use http://www.isibang.ac.in/ns/mod#ontologyInUse
(not that URI are not persistent yet)

**Comment by cmungall** [comment]
That link is dead...

But it's not enough to use a single triple. We either need to reify the triple or create a usageInstance (we do the latter now). For OBO Foundry purposes it is not sufficient to say X uses Y. We want to know of the usage: what kind of usage, what is the reference, what is an example, is the verified by the OBO Foundry, etc. Have a look at the usage field in some of the yamls

**Comment by nlharris** [comment]
Is this done or still needed?

**Comment by nlharris** [comment]
Closing; reopen if needed.
