### ISSUE TITLE
MFOMD

### ISSUE THREAD

**Issue by phismith** [OBOFoundry/OBOFoundry.github.io#632]
please change the page for 

http://www.obofoundry.org/ontology/mfomd.html

by removing MFO from the title. To solve the problem with 

http://www.obofoundry.org/ontology/mfo.html

given that the latter is depracated, perhaps you can change the url to 

http://www.obofoundry.org/ontology/depracated/mfo.html

or something
BS

**Comment by cmungall** [comment]
> http://www.obofoundry.org/ontology/mfomd.html

hmm, the PURLs for this ontology are all MFOMD_nnnnnnn

we don't explicitly require that the title field is a spelling out of the identifier space, it's potentially confusing when these don't match up. Can you or Janna recall why the MFOMD ID space was used in this first place?

Perhaps we can change the title but include an explanatory note: "This ontology uses PURLs in the MFOMD ID space because the original title was..."?

> To solve the problem with
> http://www.obofoundry.org/ontology/mfo.html
> given that the latter is depracated, perhaps you can change the url to
> http://www.obofoundry.org/ontology/depracated/mfo.html

is there actually a problem here? Currently we don't change the URL for an ontology when it is deprecated. The page clearly states the ontology is deprecated.

It is perhaps unfortunate that there is potential confusion between mfo and mf:

http://www.obofoundry.org/ontology/mf.html

but formally the prefixes are different and there is no clash

For new ontologies coming in we try and do a better of policing the ID spaces, and would try and avoid have both XX and XXO, since there are frequently synonymized (e.g. the ontologies for which the OBO ID space is MP and HP are frequently referred to as "MPO" and "HPO"). But unfortunately there are a handful of grandfathered in ontology pairs only differentiated by the "O" - VT and VTO, MF and MFO

**Comment by phismith** [comment]
Originally the idea was that MF would be the hub ontology, and MF-EMO,
MF-MDO, ... would be extensions.
At some point an error was made, so that MFOEM and MFOMD were used instead.
Does this help to determine the neatest solution?
BS

**Comment by cmungall** [comment]
You can see the proposed changes here: https://github.com/OBOFoundry/OBOFoundry.github.io/pull/635/files

If you see a "Review" button you can approve changes there.. or just here in this ticket if easier
