### ISSUE TITLE
Support for multiple contacts - which include ORCIDs

### ISSUE THREAD

**Issue by agbeltran** [OBOFoundry/OBOFoundry.github.io#73]
I think it would be useful to allow for multiple contacts for an ontology, including multiple people or mailing list(s).

**Comment by cmungall** [comment]
+1 for single primary contact (continue to use 'contact' field) and any number of additional contacts

**Comment by agbeltran** [comment]
It seems that #33 would require this, as well as STATO.

**Comment by zhengj2007** [comment]
If I remember correctly, based on OBO Foundry policy, only one person is allowed for ontology contact. Sorry, I cannot find where it is documented.

**Comment by scheuerm** [comment]
I agree with Chris M., +1 for single primary contact (continue to use 'contact' field) and any number of additional contacts

**Comment by mbrochhausen** [comment]
I also agree with Chris': +1 for single primary contact (continue to use 'contact' field) and any number of additional contacts

**Comment by cstoeckert** [comment]
+1 for single primary contact (continue to use 'contact' field) and any number of additional contacts.
The 'locus of authority' principle (#11) names a Contact Person as "a single person who is responsible for communications...". So need to be unambiguous about which contact serves that role.

**Comment by batchelorc** [comment]
I'm with Mathias on this. And Chris by the looks of things.

**Comment by mcourtot** [comment]
I'm on the fence. I could live with the 1 primary contact and additional, but I'm wondering if the need for additional doesn't stem from the old association with "contacts = credit". If we have a single contact and for example a mailing-list, do we really need additional contacts as well? Perhaps if the rational for the request could be expanded a bit more, maybe with use cases explaining why this is desirable?

The big argument in favour of having a single contact is to have one responsible person - having many contacts has the potential to open the door to no one taking care of the request ultimately (thinking someone else did)

**Comment by agbeltran** [comment]
The request wasn't based on contacts = credit (as this would imply having potentially many contacts) but considering that there might be a few (two or three possibly) responsible people that could reply to requests rather than a single person. Thanks.

**Comment by cmungall** [comment]
In general I would encourage ontologies to encourage the use of the tracker for most requests. For users who don't want to do this, don't want to get a login, etc, then a help email or helpdesk type URL is a good idea (we should have a proper field for this - what RDF property would this be?). The contact is primarily for OBO central to communicate with the ontology maintainers (maybe now it's easier to introspect this from github, but this may not always be the optimal route). Maybe we show it too prominently on the site

**Comment by cmungall** [comment]
Notes from call with Peter McQuilton: if we can add an ORCID field for contacts this could make synchronization with biosharing easier

**Comment by cmungall** [comment]
Often the contact field is an admin email address rather than a person. Do we want to push on this?

I'm OK with this. I think that since the time the original principle was formulated, having a github tracker is more important than strict adherence to single POC

**Comment by cmungall** [comment]
Since originally commenting on this I have encountered a few cases where two curators would like to be listed as contacts, so I am now open to changing the cardinality.

However, we should make clear that contact != credit, provide other means for providing people credit with roles in developing an ontology, and encourage use of GitHub trackers rather than 1:1 emails. I would like the contact(s) not to be shown on the OBO site, as the only use case for them AFAICT is as a POC for OBO purposes such as OBO review (and even here we should go via tracker)

**Comment by matentzn** [comment]
I 100% agree with that; contacts are way too easily conflated with credit, no matter what we write in the smallprint. Email addresses and names should not be displayed. As an aside: If you remember, I was also working on a [visualisation](http://rpubs.com/matentzn/ro2018) for the provenance of OBO foundry ontology contributions; these would be made much easier if I had access to contributor (or as a compromise 'contacts') orcids. Aside over.

**Comment by mellybelly** [comment]
I agree also. In the old days, we had made the requirement to have a person listed to due to there being too many out-of-date listserves used, making it hard to find the actual people to follow up with. I think we could easily just have the contact listed as part of the registration, and check these for currency say 1X/year. "contact" could then be any email address, list, or help desk email. This might help with the credit issues.

**Comment by mellybelly** [comment]
lets have this as a separate field; the problem earlier was that it was the contact address and often went stale. What do you think?

**Comment by matentzn** [comment]
Yeah I guess thats true (publicness of email).. The working group email has to be public.. I am sure we could make that a requirement?

Staleness argument does not fascinate me too much because we have the same with people: arent they jumping around from institution to institution as well?

Anyways, dont worry about me. I just dont like the idea of a primary contact because of the credit issue, but I dont want to be a blocker here. Lets do how you say :)

**Comment by nlharris** [comment]
what's the status of this?

**Comment by nlharris** [comment]
Can this be closed?

**Comment by matentzn** [comment]
I think this ticket has become to multi-faceted to be useful. The original request: support multiple contacts is denied, so now the other questions (group emails vs. individuals; etc) should just get there own tickets. I would close this for now.
