### ISSUE TITLE
Broken link of "xlmod"

### ISSUE THREAD

**Issue by zhengj2007** [OBOFoundry/OBOFoundry.github.io#825]
The links of xlmod and its 'details' do not work on the OBO Foundry home page:
http://www.obofoundry.org

**Comment by cmungall** [comment]
May be related #71

**Comment by simonjupp** [comment]
I think this might because the file has the wrong name in the repo `xmlmod.md` should be `xlmod.md`, right?

https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/ontology/xmlmod.md

We also have a related issues here EBISPOT/OLS#246 where the author is asking if we can pull the file from http://ontologies.berkeleybop.org/xlmod.obo which I presume is coming from https://raw.githubusercontent.com/HUPO-PSI/mzIdentML/master/cv/XLMOD.obo?

**Comment by cmungall** [comment]
Good catch, can someone do a git mv?

**Comment by nlharris** [comment]
Who could that "someone" be?

**Comment by jamesaoverton** [comment]
Fixed by 810609b061495d4b89f5af0afa72cac74eba27e2
