### ISSUE TITLE
consistency of namespaces (eg PO)

### ISSUE THREAD

**Issue by VladimirAlexiev** [OBOFoundry/OBOFoundry.github.io#844]
Following some discussion and encouragement by @cmungall (https://twitter.com/chrismungall/status/1105540932315815936) I'll start posting AgroBio ontology problems that I found in the frame of the BigDataGrapes project. You can find them in one place at [BigDataGrapes D3.1 - Data Modelling and Linking Components](https://doi.org/10.5281/zenodo.1482757) section 3 (with some background in section 2), and a bit more details in https://github.com/BigDataGrapes-EU/ontology/blob/master/notes/README.org.

The first problem is consistency of namespaces. 
Eg PO uses namespace <http://purl.obolibrary.org/obo/po#>.
However the ontology is served from <http://purl.obolibrary.org/obo/po.owl>.
If you try to resolve the ontology namespace, you get http://ontologies.berkeleybop.org/# which is not even RDF

**Comment by balhoff** [comment]
Hi @VladimirAlexiev you might be interested to read the [OBO Foundry Identifier Policy](http://www.obofoundry.org/id-policy.html).

But I found only 21 "terms" in PO with IRIs beginning with `http://purl.obolibrary.org/obo/po#`. These are almost all "subset" definitions, which are essentially just non-logical tags on OWL classes, used for various filtering use cases. There are two which seem to be "local" object properties minted by PO, which perhaps they feel aren't general enough to be submitted to the Relation Ontology. The format of these IRIs is kind of a consequence of how these are mapped to the `subset` tag in OBO format.

Terms managed by PO should all begin with the IRI pattern `http://purl.obolibrary.org/obo/PO_` followed by a local numeric identifier. However you will ideally find terms from other "namespaces" within the ontology, if they are reusing terms from other OBO ontologies as appropriate (in PO I see at least `http://purl.obolibrary.org/obo/RO_` and `http://purl.obolibrary.org/obo/BFO_` terms.

I guess you would prefer to see term IRIs have the same prefix as the ontology IRI, but in my opinion that somewhat contradicts reusing terms from other ontologies. In OBO, one ontology project may also produce several different ontology "products" which each has its own ontology IRI. But the "main" product is typically available at an IRI based on the ontology project ID (e.g. PO) in this form: http://purl.obolibrary.org/obo/po.owl

When resolve that IRI, I get the ontology. An individual term IRI should resolve to a description at OntoBee (unless that is overridden by a configuration for a particular project). For PO this works correctly for the "properly" structured term IRIs, but not for the `http://purl.obolibrary.org/obo/po#` ones.

I think we could do better at linking terms to their "source" ontologies within the RDF returned from (e.g.) OntoBee (I think there's a ticket about this somewhere). In my opinion it would be better done in RDF rather than having people destructure IRIs, which should just be treated as opaque identifiers.

I'd be curious if any of this addresses your concerns! We can probably do a better job at documenting OBO conventions and also making them more discoverable.

**Comment by cmungall** [comment]
@alanruttenberg do you want to comment on this one?

**Comment by alanruttenberg** [comment]
I think Jim's note nailed it. We recommend not using fragments for ontology
term IRIs precisely to avoid issues such as those Vladimir observes.
Best,
Alan

**Comment by nlharris** [comment]
what is the status of this?

**Comment by nlharris** [comment]
I'm tempted to close this one because it's so old and no one seems to be pursuing it. Please reopen if desired!

**Comment by VladimirAlexiev** [comment]
@balhoff @nlharris I checked the URLs in my original comment and they still don't work ok.
Maybe PO is unimportant,  but as the original comment says, that's just an example. 

Could you please document here the resolution of some commonly used agro-bio ontology terms?

**Comment by balhoff** [comment]
@VladimirAlexiev most terms in PO are of this form: `http://purl.obolibrary.org/obo/PO_0009049` ([inflorescence](http://purl.obolibrary.org/obo/PO_0009049)). These resolve. The only problem I'm aware of is the unresolvable subset identifier terms which I mentioned above, but there are only a few of those, and there is no requirement that they resolve anyway (although it would be nice). Are there any other issues you see?
