### ISSUE TITLE
Should travis job of md submission check whether products are ROBOT parseable?

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#845]
Would be cool to ensure that purl actually works before merging.

**Comment by matentzn** [comment]
(alternatively check this for purl config)

**Comment by jamesaoverton** [comment]
We've considered this in the context of the OBO PURL system and OBO-wide testing. It would be a nice feature, but it's trickier to implement than it might seem at first glance.

Our current system uses the free version of Travis CI, and we want it to pass or fail quickly, so we need to take a very lightweight approach. We currently just validate all the `.md` files, without distinguishing which one(s) were changed.

If we did distinguish which ones had changed, then we could get a short list of products. We could try an HTTP HEAD request for each, which should eventually return a 200 status code without actually downloading the ontology. This would at least tell you that *something* is there. Some servers don't handle HTTP HEAD very well, there's no equivalent for FTP, and you have to handle network delays and failures. I worry about false negatives and false positives.

Rather than try and make this work with Travis, I think it would be better to do these checks as part of an editing system (#820), or as part of a more powerful system for consistency checks (#778).

**Comment by cmungall** [comment]
Also this problem may be more sociological. It's rare for established ontologies to completely disappear. Most ontologies not marked obsolete are resolvable. There is a small set that are not marked obsolete that we seem to be stuck in a loop discussing, is there someone to take it over and create a github repo, who will take it over, finding out who to contact.

So maybe the gain would be minimal.

**Comment by matentzn** [comment]
Yeah, you are right. I will keep posting when I encounter broken purls though :P!
