### ISSUE TITLE
New ontology request form - next steps

### ISSUE THREAD

**Issue by nataled** [OBOFoundry/OBOFoundry.github.io#882]
This issue is to discuss the options, requirements, and pipeline for use of the form created for registering new ontologies. The contents of the form itself has already been discussed by the Operations Committee, and minimally revised (including the title) based on feedback both from that discussion and from a test user. The form is here:

https://docs.google.com/forms/d/1CAKREF73rPiBVGEGubzWJlSWTZfWwWCaf5iJ6YjwQ1k/edit

In addition to ontology registration, this form is intended to prompt ontology developers to think about Foundry principles. As such it is intended to replace registration via email. The Editorial WG proposes the following:

1) Amend the "New Ontology Request" template:
 a) To point to this form. Possible wording:

"To register your ontology, please fill out the Google form at https://forms.gle/uyZNETjT4WpRothw6 to the best of your ability. Upon completion, please comment such as a follow-up to this tracker item."

 b) Other than when someone is assigned, how do we find out a form has been filled?

2) We need to insert this form into the appropriate pipeline. 
 a) If there is there a way to generate a notification upon completion, we would not need the "please follow-up" request indicated in (1) above.
 b) Perhaps there is a way to automate the generation of the needed files (YAML, MD)?
 c) Would be good to automatically generate an obo-discuss email.

**Comment by nlharris** [comment]
> Other than when someone is assigned, how do we find out a form has been filled?
Have you considered using issue templates (instead of a Google Form) to allow users to submit requests to have new ontologies added? That would automatically create a GitHub issue for each new ontology request, which would be seen by anyone watching the repo. The issue templates aren't quite as simple for users as a Google form, but they're not bad.
You may have already discussed using issue templates and decided that wouldn't work well for this purpose?

If you decide to stick with the Google form, there is apparently a way to make it generate email when someone submits a response (by adding scripts to the form): https://medium.com/@max.brawer/learn-to-magically-send-emails-from-your-google-form-responses-8bbdfd3a4d02
(I haven't tried that)

Regarding the instructions to users, I think this is a bit unclear:
> Upon completion, please comment such as a follow-up to this tracker item.
How about something like, "After submitting the New Ontology Request form, please add a comment to this issue [URL] to alert the OBO Foundry staff." This instruction could be added to the confirmation message that users see when they submit the form. (You can set that in Settings -> Presentation -> Confirmation message.)

Hope this helps!

**Comment by nlharris** [comment]
Note that @cmungall already created an issue template here: https://github.com/OBOFoundry/OBOFoundry.github.io/issues/new?assignees=&labels=new+ontology&template=new-ontology-request.md&title=
last week. There may be some reason you decided to proceed with the Google form rather than with the issue template that I'm not aware of.

**Comment by nataled** [comment]
Thanks for your suggestions! The Form was created and discussed before the template. Both options are on the table though. We basically agreed that the form is more user-friendly, but if we can't do some automation with it, it might be abandoned. If it does get abandoned, the template would be revised to incorporate (to the extent possible) the information from the form. It would be nice if the template could be made prettier.

**Comment by nlharris** [comment]
What is the status of this ticket? Are modifications to the form needed?

**Comment by nataled** [comment]
I believe we have a few modifications in mind, but these need to be coordinated with other forms. If anything, the issue template would require major changes to incorporate the information that's currently provided on the form (things like instructions).

**Comment by nlharris** [comment]
Seems like a decision needs to be made about this. I think the issue template is already publicly available; not sure whether the Google form is. #1246 suggests directing new ontology submitters to use the issue template (without mentioning the form). I think the main question is how easy you want to make it for people to submit new ontologies; in particular, do you want people who don't use GitHub to be able to submit their ontologies for consideration? That could put a heavier burden on OBO Foundry staff, as those ontology owners won't be able to do PRs to update information about their ontologies, so they might ask us to do it.

**Comment by nlharris** [comment]
BTW, it looks like all the fields in the form (https://docs.google.com/forms/d/e/1FAIpQLSe0kHFST4K6nPiwcz_ylXI8dZF88Ziv7e5tWES1KOy--CDqvg/viewform) are also in the template (https://github.com/OBOFoundry/OBOFoundry.github.io/issues/new?assignees=&labels=new+ontology&template=new-ontology-request.md&title=), so it appears that this has already been satisfied:
>   the template would be revised to incorporate (to the extent possible) the information from the form
Regarding this:
> It would be nice if the template could be made prettier.
what do you mean by "prettier"?

**Comment by nlharris** [comment]
So what should we do about this?

**Comment by nataled** [comment]
This issue--form vs template--is driven mostly by the needs of the technical people. It is my understanding that the template is the desired method, but it's unclear just how it all should work. If someone can describe the process in more detail, the EWG can play with the writing. "Prettier" (not sure this still applies) just means easier to look at and fill. At the time, it wasn't so easy to do.

**Comment by jamesaoverton** [comment]
Yes, the core technical problem is that our workflows are centred on GitHub issues and pull requests. It's a bit tricky to connect a nice form to GitHub workflow.

The GitHub issue templates have been working OK.

My team is developing a form (based on the Google Form) that will integrate properly with GitHub issues, and with our registry and PURL files. It needs a bit more work before we ask OBO Operations to review it.

**Comment by matentzn** [comment]
I think, for now, we will stick with the GitHub issues! I will close this for now.
