### ISSUE TITLE
Principle #3 "URI/Identifier Space"

### ISSUE THREAD

**Issue by nataled** [OBOFoundry/OBOFoundry.github.io#954]
Current text:

**Details**

Each class and relation (property) in the ontology must have a unique URI identifier. The URI should be constructed from a base URI, a prefix that is unique within the Foundry (e.g. GO, CHEBI, CL) and a local identifier (e.g. 0000001). The local identifier should not consist of labels or mnemonics meaningful to humans. Additional information is available at http://www.obofoundry.org/id-policy

The ID-space / prefix must be registered with the OBO library in advance. Please see the relevant documentation.

**OBO-Format Ontologies**

If the source ontology is in OBO-Format, then this is automatically satisfied so long as all IDs are of the form <IDSPACE> : <NUMBER>

**Comment by nataled** [comment]
1) From https://github.com/OBOFoundry/OBOFoundry.github.io/issues/600
The technical group would like to ask the editorial group to formulate a policy about (1) resources need to have broad enough scope to request prefix (2) shorter prefixes should be allocated to broader scope resources

2) Some things to consider, from EWG call 17/04/2018: URI policy: Application ontologies vs reference ontologies; should that matter? How do we decide what is ‘broad’? Ontologies with narrow scope should not have short (2? 3?) prefixes. What is 'short'?

3) Should this be extended to include standardized PURLs?

ACTION: Rewrite as is, but consult with OFOC about PURLs (products)

**Comment by ramonawalls** [comment]
Updated that has been reviewed by Editorial WG. Please comment.

## Principle 3: URIs

**Name:** Unique IRI/identifier space

### Summary
Each ontology MUST have a unique IRI in the form of an OBO Foundry permanent URL (PURL). The PURL must include the ontology namespace, which is abbreviated by a short set of letters approved by the OBO Foundry Operations Committee. Every element (class, property, etc.) created by the ontology MUST use the namespace in the identifier of each element, as specified in the OBO Foundry ID policy. Imported elements need not follow this requirement.

### Purpose 
A unique namespace within the OBO Foundry Library allows the source of an element or term (e.g., class, property) from any ontology to be identified immediately by the prefix of the identifier. It also allows ontology element IRIs to be shortened to a compact URI or CURIE, which allows developers to use CURIES for working with ontologies. OWL syntax allows for ontologies and their elements to have identifiers in the form of an IRI. The OBO Foundry uses IRIs in the form of PURLs  to allow an ontology and its elements to be resolvable (findable on the web). PURLs are URLs (and thus locate the resource) that are permanent or redirectable, allowing the URL to point to a new location when the resource moves. OBO Foundry PURLs use a standard format that includes the ontology namespace so that they can be easily maintained by a group of volunteers, and so ontology maintainers can update the location their PURL points to using a GitHub pull request. 

### Recommendation

#### Implementation

##### Ontology Namespace:

The namespace is a short string of letters (usually 2-5) that is representative ontology. When used as part of a CURIE, on its own, or as part of a term ID, the namespace is generally capitalized. When used as part of the ontology IRI, the namespace is in lower case. See examples below

To request a new namespace, ontology developers MUST follow these guidelines. Note that very short namespaces (2-3 characters) are reserved for ontologies that cover a general domain and are likely to be frequently used.

##### Ontology IRI:
The primary IRI for an OBO Library IRI MUST have the following format:
https://purl.obolibrary.org/obo/$namespace.owl
or 
https://purl.obolibrary.org/obo/$namespace.obo

Ideally, both versions of the ontology should be available. To conform with OBO Foundry principles, the ontology IRI should resolve to the ontology file, not a landing page.

For guidelines on how to create IRIs for ontology elements/terms, see the ID policy.

#### Examples
http://purl.obolibrary.org/go.owl
http://purl.obolibrary.org/go.obo
http://purl.obolibrary.org/pcoo.owl

#### Counter Examples
The following counter examples are valid ontology IRIs, but do not conform with OBO Foundry principles. 

http://iridl.ldeo.columbia.edu/ontologies/SWEET.owl

Furthermore, these IRIs do not resolve to the ontology file.

http://purl.org/dc/terms/

http://dbpedia.org/ontology/


### Criteria for Review:

The ontology namespace is registered at http://www.obofoundry.org/ following the procedures outlined at http://www.obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html 
The ontology IRI follows the format above.

**Comment by matentzn** [comment]
the ontology IRI should resolve to the ontology file, not a landing page. -> MUST not should I would say

**Comment by jamesaoverton** [comment]
I think that http://purl.obolibrary.org/pcoo.owl should be http://purl.obolibrary.org/pco.owl

**Comment by cstoeckert** [comment]
Move "Imported elements need not follow this requirement." from Summary to Implementation section. (discussed on OBO operations July 28, 2020 call).

**Comment by cstoeckert** [comment]
The Examples are incorrect. Needs an /obo/

**Comment by bpeters42** [comment]
@nataled You mentioned in the dashboard issue #51 that this issue for the principle spells out that term identifiers can be alphanumeric; But all I see in this rewritten version is information about the link to the ontology itself? And a reference to the ID policy, which in itself is not clear to me where I should look?

**Comment by nataled** [comment]
@bpeters42 that's because the principle is not really about the local ID part of the identifiers. I edited the text above to provide the link to the ID policy document.

@cstoeckert looks like the correction is in place.

@matentzn I revised the text to address the MUST vs should issue.
