### ISSUE TITLE
Principle #16 "Maintenance"

### ISSUE THREAD

**Issue by nataled** [OBOFoundry/OBOFoundry.github.io#959]
Current wording:

NOTE
-------
The wording of this principle is still in progress.

Summary and Purpose
-------
The ontology needs to reflect changes in scientific consensus to remain accurate over time.

Implementation
-------
Ideally, the maintainer of an ontology should actively monitor for any changes in scientific consensus, but at a minimum, the maintainer needs to be responsive in a timely manner (less than 3 months) to requests from the community pointing out such changes in scientific consensus. Tentatively, we consider scientific consensus to be reached if multiple publications by independent labs over a year come to the same conclusion, and there is no or limited (<10%) dissenting opinions published in the same time frame. In cases an area remains controversial, and no consensus is reached, then it is up to the ontology maintainer to either leave out the controversial term, or pick a viewpoint for practical considerations, and note the presence of controversy in an editor note.

Review Criteria
-------
The developers of the ontology need to include a statement specifying how they are planning to maintain the ontology. We expect that an ontology will be maintained for at least 3 years from the time of review.

**Comment by nataled** [comment]
@nataled : I suspect this principle is one that we would not be able to validate in any systematic way. Perhaps a long-standing ontology can be reviewed by looking at the history.
Releases?
Changes?
Statement indicating that it has been done? (Can be that a grant has been funded; issue tracker activity)
Maybe statements about domain expert consultation or use of accepted standards?

**Comment by cmungall** [comment]
I suggest having this principle be more a mission statement and un
reviewed. Perhaps auto pass unless there is a clear violation e.g ontology
claiming opposite of consensus and unwilling to change

**Comment by nataled** [comment]
This is an 'accepted' principle from years ago. Demoting it would take an Operations discussion. As I stated above, I'm not sure how to evaluate it, and therefore I'm inclined to agree with doing so.

**Comment by cmungall** [comment]
I'm not sure I follow. I don't know what demoting means in this context.
All principles on the site are by definition accepted unless there is some
nomenclature I'm not aware of. Let's just iterate on making the principles
clear and operational via issues and PRs. No need for operations call
discussion unless something difficult arises?

**Comment by nataled** [comment]
My mistake, I interpreted your suggestion that it be unreviewed as a desire to remove it from the principles (hence, 'demoted' from "is a principle" to "is not a principle").

**Comment by ramonawalls** [comment]
Revised wording to review on the Ops call:

# Principle 

## Summary

The ontology MUST reflect changes in scientific consensus to remain accurate over time.

## Purpose


## Recommendations

Scientific consensus is considered to be reached if multiple publications by independent labs over a year come to the same conclusion, and there is no or limited (<10%) dissenting opinions published in the same time frame. In cases where an area remains controversial, and no consensus is reached, then it is up to the ontology maintainer to either leave out the controversial term, or pick a viewpoint for practical considerations, and note the presence of controversy in an editor note.

### Implementation

At a minimum, the maintainer MUST be responsive in a timely manner (less than 3 months) to requests from the community pointing out such changes in scientific consensus. The maintainers of an ontology SHOULD actively monitor for any changes in scientific consensus. 

### Examples

Active issue tracker discussing terms along with corresponding updates to the ontology.

Documentation of community discussions at workshops or conferences.

### Counter-examples

No commits for >1 year.

No discussion with community.

## Criteria for review

During review: The developers of the ontology MUST include a statement specifying how they are planning to maintain the ontology. We expect that an ontology will be maintained for at least 3 years from the time of review.

Ongoing:  The ontology was updated within the past year.

**Comment by cmungall** [comment]
I'm a bit confused by this. It seems there are two related but quite distinct things:

 1. scientific consensus
 2. generally being responsive and ensuring the ontology is well-maintained

While 1 is obviously of vital importance, I'm not sure it's such a useful concept for 99% of maintenance and development of most ontologies, the literature generally reflects consensus, and the ontology follows the literature. For sure, we should have some kind of safeguard against people making loch ness monster ontologies or minting axioms that state that climate change is not majority anthropogenic, but I think this can be framed independently of frequency of github commits.

Do we have an example github issue where someone has posted regarding scientific consensus?

The examples and counter-examples given all seem to pertain to 2, and don't necessarily hinge on consensus or doing complicated literature meta-analyses. 2 seems a nice practical operational criterion.

Given the name "maintenance" I suggest budding off scientific consensus into its own principle and keeping this principle focused on basic metrics of responsivity. This MAY be git commits, it SHOULD reflect engagement on open issue trackers, where requests are either fulfilled or reasons provided (e.g. "we make this change but it's complicated as we have to first refactor area A of the ontology, and we have limited resources, and this is not a priority..."). The number of uncommented issues (total and within the last year) SHOULD be below a certain fraction (10%?).

Additional comments:

 - the 'active' status of ontologies should be discussed here. Ontologies that are no longer maintained may be marked inactive (this is not necessarily indicative of quality, I have marked ontologies I work on as inactive before)
 - the '3 years' seems arbitrary and its relationship to enforceability is not clear. I would restate that ontologies SHOULD be maintained in perpetuity, but we live in a world of limited funding (and externally driven priorities when funding is available), changing circumstances, and that inactive ontologies may be marked as such so that users are better informed.
 - need examples of what a maintenance plan is. Without further guidance we are asking people to do vague busy work that can't be evaluated meaningfully and doesn't contribute to the goals of OBO

**Comment by nataled** [comment]
In early discussions we did indeed break this into two principles: 'maintenance' (16) and a new proposed principle 'responsiveness' (20).

**Comment by cmungall** [comment]
I guess that's not the split I'm proposing here

**Comment by nataled** [comment]
@cmungall wrote:

1.    scientific consensus
2.    generally being responsive and ensuring the ontology is well-maintained

Your #1 is this principle (16), while your #2 is the new (not yet discussed) principle 20. Unless your concern is that 'this' principle is the responsiveness principle and the new one should be consensus? That's actually not the case, historically, despite your interpretation of the shorthand name (if I recall correctly, the actual name is 'maintenance in light of scientific advance').

**Comment by nlharris** [comment]
see also #960

**Comment by nataled** [comment]
Closing since both of the related principles discussed here are finished.
