### ISSUE TITLE
PROPOSED Principle #20 "Responsiveness"

### ISSUE THREAD

**Issue by nataled** [OBOFoundry/OBOFoundry.github.io#960]
Initial thoughts/text:

Name: Responsiveness to community term requests

(text moved from #10) Recommendation:It is required that ontology developers offer channels for community participation. A discussion mailing list and issue tracker are required to obtain an OBO Foundry PURL. It is recommended to aim for a good level of responsiveness to community requests and suggestions, which is also related to the maintenance principle (#16). 

Issue tracker:        https://github.com/geneontology/go-ontology/issues/ 
Discussion list:     go-discuss@mailman.stanford.edu
Collaboration of this sort can be demonstrated by having an active discussion mailing list, responsiveness to community requests

**Comment by cmungall** [comment]
The text here looks very old. Most onts do not have a mail list. All should
have an open issue tracker,  e.g github or gitlab

**Comment by nataled** [comment]
Yes, this is old text. I'm capturing the latest information from the principles working document to ensure we use the tracker for discussions instead.

**Comment by nataled** [comment]
Assigned to @nicolevasilevsky

**Comment by matentzn** [comment]
For me this principle is so central to OBO, I am almost inclined to quantify it explicitly on the dashboard. Using the github api, we can measure how many tickets are not being responded too, and my guess is that we can do the same for bitbucket and gitlab as well.. So good level of responsiveness for me is that any issue is responded to within 2 weeks of the issue request (more is bad smell). I think we should recommend something about (not enforce it) along these lines:

---------------

Tickets, including new term requests and bug reports, are fundamental to open science initiatives such as OBO. Writing any ticket takes time, but writing good tickets can be a serious amount of work that is often overlooked - many of our ontologies simply would not continue to evolve without them. It is therefore imperative that issues are treated with great care. The OBO Foundry offers the following recommendations on the responsiveness in issue trackers.
1. Issues are contributions - and should be met by a thankful attitude. When receiving a ticket on your issue tracker, the first thing you should do is thanking the contributor.
2. Even if you can't deal with a ticket right away, offer your thanks, and explain when you plan to look at the ticket in more detail. This should happen soon after a ticket is issued - ideally in the first 2-5 working days after the issue entered your tracker. This gives the ticket issuer the confidence that they are heard - and increases their inclination to continue making issues. _Many people have been known to stop creating issues just because they thought no one was listening!_
3. Do not close tickets just because you don't like them - closing ticket without allowing the issuer to come to a conclusion is rude by all standards. If you think a ticket is out of scope for a repository, recommend to move it to a different repo.
4. To guarantee the above, make sure that you don't only _have_ an issue tracker, but you have someone that feels responsible for it!

"Responsiveness" is a key quality of our general collaborative spirit.

**Comment by drseb** [comment]
I agree that it is very important to motivate the community to contribute to the ontologies. Being friendly and responsive is a prerequisite for continued support from the community

**Comment by nataled** [comment]
Note: this is technically not a 'new' principle. It emerged from extensive discussion within the EWG many years ago when we realized that there was some overlap in the (then-current) wording and intention of Collaboration (10) and Maintenance (16). Thus, in terms of acceptance as principle, it's existed from before the formation of the Operation Committee et al. The only issue here is wording (the focus of this ticket).

That being said, upon re-looking at the issue, we discussed rolling this back into either 10 or 16 (with the latter being favored), but ultimately decided to keep it separate for automated check purposes. Currently the tracker check has been implemented (incorrectly, IMO) as part of the Users (9) principle. Once this is implemented, that check would be for this principle instead.
